### PR TITLE
Prepare ivf for publishing

### PR DESCRIPTION
**Pull request by lu-zero**
Addresses #1197

### CODE REVIEW

**Comment by eclipseo** [comment]
Could you add a License file in the crate too please?

**Comment by lu-zero** [comment]
Doesn't seem needed from what I could [read](https://doc.rust-lang.org/cargo/reference/manifest.html#package-metadata)

**Comment by eclipseo** [comment]
> Doesn't seem needed from what I could [read](https://doc.rust-lang.org/cargo/reference/manifest.html#package-metadata)

Needed by downstream Linux distro.

**Comment by lu-zero** [comment]
If you have time to send a PR I'd merge it immediately :)

**Pull request merged**
