### PR TITLE
Prepare for 0.6.0 release

### PR DESCRIPTION
**Pull request by shssoichiro**

### CODE REVIEW

**Review by lu-zero — APPROVED** [review]

**Comment by shssoichiro** [comment]
@lu-zero whenever you're ready to pull the trigger, since you have crates.io publish rights:

- Merge this
- Pull it down
- `cargo update` (since we don't use lock files)
- `cd ivf && cargo publish && cd ..`
- `cargo update` again to pull in new ivf version
- `cargo publish` for rav1e :tada: 
- Create and push git tag

**Comment by lu-zero** [comment]
You forgot the part about creating the branch for 0.6.x :)

**Comment by EwoutH** [comment]
Did the 0.6.0 release ever materialize? It would be great to have a new stable release!

**Comment by lu-zero** [comment]
I'll try to get it out, I hadn't time to prepare the release notes with all the benchmarks.

**Comment by EwoutH** [comment]
No worries, these things take a lot of effort.

Are the benchmarks the main culprit or the release notes itself? There are some tools for (semi-)automatic release note generation, I could suggest a setup if you did like that.

https://github.com/xiph/rav1e/projects/20 is an impressive looking list by the way!

**Pull request merged**
