### PR TITLE
Reverse skip/no-skip search for chroma mode.

### PR DESCRIPTION
**Pull request by tdaede**
This makes skip win ties over no-skip.

https://beta.arewecompressedyet.com/?job=master-e82003643aa440c02d3c6669cd49b529567ef277&job=chroma_reverse_order%402019-07-22T01%3A47%3A48.466Z

master-e82003643aa440c02d3c6669cd49b529567ef277 -> chroma_reverse_order@2019-07-22T01:47:48.466Z

   PSNR | PSNR Cb | PSNR Cr | PSNR HVS |    SSIM | MS SSIM | CIEDE 2000
-0.1993 | -0.1852 | -0.3532 |  -0.1811 | -0.1777 | -0.1736 |    -0.1683

### CODE REVIEW

**Comment by ycho** [comment]
I am trying to figure out where the 0.2% gain comes from. We see that rdo_tx_size_type() is now called for each chroma mode being tested (with given luma mode), instead of each luma mode only. We wanted the function called for each luma mode only since we believed that only luma pixels/info are required to decide tx_type at that time.

**Comment by tdaede** [comment]
I tried moving *just* rdo_tx_size_type(), but there is no awcy difference: https://beta.arewecompressedyet.com/?job=master-e82003643aa440c02d3c6669cd49b529567ef277&job=just-tx-rdo-fix%402019-07-22T19%3A35%3A08.035Z

**Comment by tdaede** [comment]
If I don't move it, then I get an assertion failure because tx_size is not set correctly for the skip case. I think with the other order, tx_size got set correctly at the end of the skip=false search by chance.

**Comment by tdaede** [comment]
Actually, with this change I can probably remove the if skip { tx_type = DCT } line because rdo_tx_size_type already sets that.

**Comment by ycho** [comment]
> Actually, with this change I can probably remove the if skip { tx_type = DCT } line because rdo_tx_size_type already sets that.

yes, that is good.

**Comment by tdaede** [comment]
updated

**Pull request merged**
