### PR TITLE
Store restoration units contiguously

### PR DESCRIPTION
**Pull request by rom1v**
The "matrix" of restoration units was stored in a vector of vectors.

To avoids an additional indirection for each row, store them in a
contiguous array instead. Besides the (theoretical) performance benerit
for every access, this will simplify the implementation of tiled-views
which have to expose non-overlapping parts of the "matrix" via unsafe
code.

Also, since its size is constant (although not known at compile-time),
replace the vector by a boxed slice.

### CODE REVIEW

**Comment by lu-zero** [comment]
if you run the tests on your local machine what happens?

**Comment by rom1v** [comment]
cargo test --features=decode_test

works (but some of them are ignored, like `test_encode_decode_aom::odd_size_frame_with_full_rdo` or all `test_encode_decode_aom::speed_XXX`.

I will amend the commit to get a new sha1 and push-force, so that the CI is run again.

**Comment by lu-zero** [comment]
`cargo test --feature=decode_test --ignored`

**Comment by rom1v** [comment]
OK, this works:

    cargo test --features=decode_test -- --ignored

:+1:

**Pull request merged**
