### PR TITLE
[WIP] Temporary fix for desync from quantizer rdo

### PR DESCRIPTION
**Pull request by ycho**
Temporary fIx for #1858.
It basically, revoke the commts from #1520 and #1564, since those commits are confirmed to cause the desync at speed 0,1,2.

Two commits that cause desync are:
https://github.com/xiph/rav1e/commit/3c79e025f7c13635558ce66370920fb5a8a38754 and
https://github.com/xiph/rav1e/commit/db0da3c97efb269cb23571f2c1f68afdf1ad9813
those needs different temporary fixes.

One set of test runs to see desync that I used can be:
./target/release/rav1e nyan.y4m -o test.ivf -r test_rec.y4m --quantizer 50 --speed=0 --limit=30
./target/release/rav1e nyan.y4m -o test.ivf -r test_rec.y4m --quantizer 50 --speed=1 --limit=30
./target/release/rav1e nyan.y4m -o test.ivf -r test_rec.y4m --quantizer 50 --speed=2 --limit=30

Note that the desync happens regardless of --tune.

### CODE REVIEW

**Comment by tdaede** [comment]
If you want a quick fix, simply disabling segmentation seems like a more straightforward fix.

**Comment by ycho** [comment]
> If you want a quick fix, simply disabling segmentation seems like a more straightforward fix.

Oh, that directs me that I forgot to not use segment.
So that, self.write_segment_data(fi, &fs.segmentation)?; signals that segment data is not written in frame header and on segment data in each partition.
Btw, fs.segmentation.enabled = true; is hard coded in segmentation_optimize() and the functions always runs even when segment is not used.

**Comment by ycho** [comment]
> If you want a quick fix, simply disabling segmentation seems like a more straightforward fix.

If you prefer that way, please go ahead since I got knockdown thanks to chasing this mess! :)

**Comment by tdaede** [comment]
OK. If segmentation = off doesn't work, we can do it this way. But you should at least merge patches 1 and 3 I think, they are two halves of the same thing.

**Comment by ycho** [comment]
> OK. If segmentation = off doesn't work, we can do it this way. But you should at least merge patches 1 and 3 I think, they are two halves of the same thing.

Sure thing. I will also try add commits that avoids not writing any seg data when not in use.
Also, please away from rav1e, you are on PTO, folk! :)

**Comment by lu-zero** [comment]
Sounds a good plan to me.

**Comment by ycho** [comment]
> OK. If segmentation = off doesn't work, we can do it this way. But you should at least merge patches 1 and 3 I think, they are two halves of the same thing.

I think the reason why I split the changes into multiple commits is to be 'minimally invasive' so that the problematic but still more code are still being compiled by our CI. Otherwise, the whole quantizer_rdo else block (i.e. non heuristic part)  needed be commented out.
I might go landing this PR (with merging commits 1 and 3 as you requested), but I am considering that another possibly better way to keep all the code and not commenting out any code would be add the condition of segment enable, i.e. "if segmentation.enable { ... }".

**Comment by barrbrain** [comment]
I agree with the recent comments, it would be preferable to have a path for disabling segmentation.

**Comment by ycho** [comment]
@tdaede , @barrbrain , following your comments, i think I've devised better way to (temporary) fix desync. See, https://github.com/xiph/rav1e/pull/1923

**Comment by ycho** [comment]
Since we have better fix which disables the use of segmentation, as in https://github.com/xiph/rav1e/pull/1923, closing this.

**Pull request closed without merging**
