### PR TITLE
WIP: Make flushing idempotent

### PR DESCRIPTION
**Pull request by lu-zero**
Ignore any other input once you start flushing.

Needs to be tested on real files.

### CODE REVIEW

**Comment by lu-zero** [comment]
@rzumer since you are already testing the lookahead cornercases, could you please give this patch a go?

**Comment by rzumer** [comment]
```
$ cargo run --release --bin rav1e -- orig.y4m --keyint 10 -s 1 -l 48 -o enc_file.ivf
   Compiling rav1e v0.1.0 (U:\dev\rav1e)
    Finished release [optimized] target(s) in 1m 57s
     Running `target\release\rav1e.exe orig.y4m --keyint 10 -s 1 -l 48 -o enc_file.ivf`
1280x720 @ 24000/1001 fps
encoded 39/48 frames, 0.247 fps, 648.38 Kb/s, est. size: 0.15 MB, est. time: 36 s
Key Frames:      7    avg size:   10876 B
Inter:          32    avg size:    1740 B
Intra Only:      0    avg size:       0 B
Switch:          0    avg size:       0 B
```

**Comment by lu-zero** [comment]
Ok so the problem is still there

**Comment by tdaede** [comment]
please rebase

**Comment by lu-zero** [comment]
Rebased, we should test it again.

**Comment by lu-zero** [comment]
Tested and it seems working fine.

**Pull request merged**
