### PR TITLE
Update the compilation profiles

### PR DESCRIPTION
**Pull request by lu-zero**
- Make the dev profile a little more optimized
- Make the other profiles have the debug information

### CODE REVIEW

**Comment by rzumer** [comment]
Seems good, but I just have a few questions:

* What is the difference in run time for debug mode?
* What is the rationale for adding debug information in release mode?
* Does setting debug to on in release mode impact performance?

**Comment by lu-zero** [comment]
>     * What is the difference in run time for debug mode?

None, for the platforms we can target (ELF, MACH-O, PE). The debug information lives in a separate sections and could even be split in a separate file to keep the actual binary lean.

>     * What is the rationale for adding debug information in release mode?
It can be used to see what is going on on a per-function granularity and it is much better than landing in the disasm world at least on mac :)
>     * Does setting debug to on in release mode impact performance?
Luckily not, our drives are fast enough that the additional size is negligible :)

**Comment by tdaede** [comment]
If debug is fast enough, we wouldn't need symbols in release. But fine for now. Not having symbols is super obnoxious.

**Comment by lu-zero** [comment]
Let see if the code coverage works on release this way.

**Comment by lu-zero** [comment]
The build time seems growing enough to have travis timeouts though...

**Comment by lu-zero** [comment]
It needs more experimentation, the time usage grow too much and using dav1d requires a new suppression map.

**Pull request merged**
