### PR TITLE
 Drop never-reached condition for creating invalid frames. 

### PR DESCRIPTION
**Pull request by tdaede**

### CODE REVIEW

**Comment by tdaede** [comment]
https://beta.arewecompressedyet.com/?job=drop-condition%402019-07-15T20%3A56%3A49.318Z&job=master-5079a62a69ec62578452ead6b9d5e5022b37996e

**Comment by KyleSiefring** [comment]
Does this need rebasing?

**Comment by YaLTeR** [comment]
> Does this need rebasing?

Waiting for my PR to land

**Comment by tdaede** [comment]
rebased

**Pull request merged**
