### PR TITLE
Automated aarch64 builds in AppVeyor

### PR DESCRIPTION
**Pull request by EwoutH**
Automated aarch64 builds for Windows.

### CODE REVIEW

**Comment by EwoutH** [comment]
Will try if I get this to work :) (all new to me).

**Comment by EwoutH** [comment]
AppVeyor now published two builds, one x86_64 and one aarch64. I asked @mstorsjo to test it, but if someone else could test the [aarch64 build](https://ci.appveyor.com/project/tdaede/rav1e/builds/21609812/job/8rye9xn9552acx11/artifacts) that would also be great (just run `rav1e --help` and then encode something random).

**Comment by EwoutH** [comment]
This latest build will not work until the `crate` for `aarch64-pc-windows-msvc` in `cargo` is updated, but when that happens this should start working (`aarch64-pc-windows-msvc` in Rust is very new and [not supported everywhere](https://mexus.github.io/rustup-components-history/aarch64-pc-windows-msvc.html) yet).

I filed a bug report here: https://github.com/rust-lang/cargo/issues/6551

**Comment by EwoutH** [comment]
If I knew Rust for `aarch64-pc-windows-msvc` targets was such a mess I never would have started it.

Anyway, it works for now. AppVeyor published artifacts again and I set a variable in the build matrix that allows the aarch64 build to fail, since it will until Rust is updated. When rust is updated aarch64 artifacts should magically start to appear.

@lu-zero If you want you can merge it. if you want to keep this open until Rust is updated that's also ok.

**Comment by lu-zero** [comment]
I'd squash+merge it now if @tdaede is fine with that.

**Comment by EwoutH** [comment]
I added a deploy function, so that AppVeyor pushes artifacts to GitHub on (pre)releases. You can see an example [here](https://github.com/EwoutH/rav1e/releases/tag/0.1.1-test3).

@tdaede Since AppVeyor runs on your account for rav1e, you need update this patch with you personal authentication token. You can generate one on https://github.com/settings/tokens/new (select `public_repo` as scope), and then encrypt it with https://ci.appveyor.com/tools/encrypt. Replace the current token on line 43 (after `secure:`).

**Comment by EwoutH** [comment]
I tried some things with the winapi-rs maintainer a few days ago, but it's a mess.

Will document the issue somewhat better over there, but let's merge this for now.

**Comment by EwoutH** [comment]
> I added a deploy function, so that AppVeyor pushes artifacts to GitHub on (pre)releases. You can see an example [here](https://github.com/EwoutH/rav1e/releases/tag/0.1.1-test3).
> 
> @tdaede Since AppVeyor runs on your account for rav1e, you need update this patch with you personal authentication token. You can generate one on https://github.com/settings/tokens/new (select `public_repo` as scope), and then encrypt it with https://ci.appveyor.com/tools/encrypt. Replace the current token on line 43 (after `secure:`).

@lu-zero @tdaede Realize the deploy function doesn't work untill the `auth_token` is replaced.

**Pull request merged**
