### PR TITLE
No coveralls

### PR DESCRIPTION
**Pull request by tdaede**

### CODE REVIEW

**Comment by barrbrain** [comment]
Let's enure that the tests that were run under kcov are still being run. It's not obvious to me on first reading that they are.

**Comment by shssoichiro** [comment]
@barrbrain is correct. The tests phase has `--ignored` which _only_ runs the ignored tests. We never run the rest of the tests.

**Comment by lu-zero** [comment]
I'd keep coveralls, I wonder if the non-kcov tools can do a better job at it.

**Comment by lu-zero** [comment]
Now I'm trying to see if we could get the same coverage with less time.

**Comment by lu-zero** [comment]
We managed to make it much more bearable, we can keep it I think.

**Pull request closed without merging**
