### PR TITLE
Cdef counter

### PR DESCRIPTION
**Pull request by xiphmont**
Add a new Writer type 'WriterCounter' that stores nothing, it merely tracks bits for cost analysis

Convert RDO to use local throwaway WriterCounters instead of checkpointing/rolling back a master Writer

### CODE REVIEW

**Comment by tdaede** [comment]
Do you have benchmarks for this? Is it expected to change performance in any way?

**Comment by xiphmont** [comment]
Thanks TD.  Waiting on review from rzumer.

**Comment by lu-zero** [comment]
Ideally you could keep a single writer and reset it when needed if the additional memory allocation costs more than a struct-wide wipe.

**Comment by tdaede** [comment]
I assume this whole thing can be stack allocated, so it doesn't matter.

**Comment by rzumer** [comment]
```
@2018-08-03T23:42:43.900Z@2018-08-03T23:43:58.900Z@2018-08-07T20:54:38.000Z -> cdef-counter@2018-08-07T20:41:05.100Z

   PSNR | PSNR Cb | PSNR Cr | PSNR HVS |    SSIM | MS SSIM | CIEDE 2000
-0.0908 |     N/A |     N/A |  -0.1210 | -0.0859 | -0.0987 |        N/A
```
I assume that this is due to moving `tell_frac()` calls.

Encoding time (Q=80): 124.766 -> 119.18

**Pull request merged**
