### PR TITLE
Speed up me by removing unnecessary cost calculation

### PR DESCRIPTION
**Pull request by takehirokj**
The same best mv can be selected by only sad.
The selected mv and output file will be same as previous one which use rate and sad.
This removal speeds up the encoding up to 1.2-7.8% in fps in my test data.

### CODE REVIEW

**Comment by lu-zero** [comment]
From what I can see the two computations aren't identical, how did you check that the results are identical?

**Comment by rzumer** [comment]
[This](https://beta.arewecompressedyet.com/?job=master-2ec50e357aa60e7c69f5fec63d4c3761c6536e53&job=takehirokj-me%402019-12-08T15%3A25%3A36.904Z) confirms that it is equivalent.

**Comment by barrbrain** [comment]
AWCY results for [this PR at default speed](https://beta.arewecompressedyet.com/?job=master-2ec50e357aa60e7c69f5fec63d4c3761c6536e53&job=takehirokj-me%402019-12-08T15%3A25%3A36.904Z) match observations by @takehirokj. I tried some quick `println!` debugging in `estimate_motion_ss4` and `lambda` was zero for the full quantizer range. Further digging showed that `fi.me_lambda` was also zero. I think the underlying bug is that `fi.me_lambda` has not been derived at the time that `estimate_motion_ss4` is called.

**Comment by barrbrain** [comment]
> I think the underlying bug is that `fi.me_lambda` has not been derived at the time that `estimate_motion_ss4` is called.

#1926 addresses the issue of zero lambda; the impact on compression is slightly positive.

**Comment by takehirokj** [comment]
I have confirm the same bug as @barrbrain.
Since this bug will be addressed in #1926, closing this.

**Pull request closed without merging**
