### PR TITLE
Add a mean to forward opaque data from Frames to Packets

### PR DESCRIPTION
**Pull request by lu-zero**
@dwbuiten please test the C-API.

### CODE REVIEW

**Comment by dwbuiten** [comment]
From the C API, the destructor is called before the user can use the opaque pointer.

**Comment by lu-zero** [comment]
Would be great writing down tests in the `capi.rs` to catch this with more ease, do you have the code handy?

**Comment by dwbuiten** [comment]
I used this patch to test it:

```diff
diff --git a/libavcodec/librav1e.c b/libavcodec/librav1e.c
index 6f9b4cce4c..16986b0123 100644
--- a/libavcodec/librav1e.c
+++ b/libavcodec/librav1e.c
@@ -416,6 +416,12 @@ end:
     return ret;
 }
 
+static void log_helper_free(void *ptr)
+{
+    printf("DESTRUCTOR CALLED!\n");
+    av_free(ptr);
+}
+
 static int librav1e_send_frame(AVCodecContext *avctx, const AVFrame *frame)
 {
     librav1eContext *ctx = avctx->priv_data;
@@ -425,9 +431,18 @@ static int librav1e_send_frame(AVCodecContext *avctx, const AVFrame *frame)
     if (frame) {
         const AVPixFmtDescriptor *desc = av_pix_fmt_desc_get(frame->format);
 
+        int64_t *pts = av_malloc(sizeof(int64_t));
+        if (!pts) {
+            av_log(avctx, AV_LOG_ERROR, "Could not allocate PTS buffer.\n");
+            return AVERROR(ENOMEM);
+        }
+        *pts = frame->pts;
+        printf("IN: %"PRId64"\n", *pts);
+
         rframe = rav1e_frame_new(ctx->ctx);
         if (!rframe) {
             av_log(avctx, AV_LOG_ERROR, "Could not allocate new rav1e frame.\n");
+            av_freep(&pts);
             return AVERROR(ENOMEM);
         }
 
@@ -438,6 +453,8 @@ static int librav1e_send_frame(AVCodecContext *avctx, const AVFrame *frame)
                                    (frame->height >> shift) * frame->linesize[i],
                                    frame->linesize[i], bytes);
         }
+
+        rav1e_frame_set_opaque(rframe, pts, log_helper_free);
     }
 
     ret = rav1e_send_frame(ctx->ctx, rframe);
@@ -519,7 +536,8 @@ retry:
     if (rpkt->frame_type == RA_FRAME_TYPE_KEY)
         pkt->flags |= AV_PKT_FLAG_KEY;
 
-    pkt->pts = pkt->dts = rpkt->input_frameno * avctx->ticks_per_frame;
+    pkt->pts = pkt->dts = *((int64_t *) rpkt->opaque);
+    printf("OUT: %"PRId64"\n", pkt->pts);
     rav1e_packet_unref(rpkt);
 
     if (avctx->flags & AV_CODEC_FLAG_GLOBAL_HEADER) {

```

And the result is pretty clear:

```
IN: 0
DESTRUCTOR CALLED!
IN: 1
DESTRUCTOR CALLED!
IN: 2
DESTRUCTOR CALLED!
IN: 3
DESTRUCTOR CALLED!
IN: 4
DESTRUCTOR CALLED!
IN: 5
DESTRUCTOR CALLED!
IN: 6
DESTRUCTOR CALLED!
IN: 7
DESTRUCTOR CALLED!
IN: 8
DESTRUCTOR CALLED!
IN: 9
DESTRUCTOR CALLED!
IN: 10
DESTRUCTOR CALLED!
IN: 11
DESTRUCTOR CALLED!
IN: 12
DESTRUCTOR CALLED!
IN: 13
DESTRUCTOR CALLED!
IN: 14
DESTRUCTOR CALLED!
IN: 15
DESTRUCTOR CALLED!
IN: 16
DESTRUCTOR CALLED!
IN: 17
DESTRUCTOR CALLED!
IN: 18
DESTRUCTOR CALLED!
IN: 19
DESTRUCTOR CALLED!
IN: 20
DESTRUCTOR CALLED!
IN: 21
DESTRUCTOR CALLED!
IN: 22
DESTRUCTOR CALLED!
IN: 23
DESTRUCTOR CALLED!
IN: 24
DESTRUCTOR CALLED!
IN: 25
DESTRUCTOR CALLED!
IN: 26
DESTRUCTOR CALLED!
IN: 27
DESTRUCTOR CALLED!
IN: 28
DESTRUCTOR CALLED!
IN: 29
DESTRUCTOR CALLED!
IN: 30
DESTRUCTOR CALLED!
IN: 31
DESTRUCTOR CALLED!
IN: 32
DESTRUCTOR CALLED!
IN: 33
DESTRUCTOR CALLED!
IN: 34
DESTRUCTOR CALLED!
IN: 35
DESTRUCTOR CALLED!
IN: 36
DESTRUCTOR CALLED!
IN: 37
DESTRUCTOR CALLED!
IN: 38
DESTRUCTOR CALLED!
IN: 39
DESTRUCTOR CALLED!
IN: 40
DESTRUCTOR CALLED!
IN: 41
DESTRUCTOR CALLED!
IN: 42
DESTRUCTOR CALLED!
IN: 43
DESTRUCTOR CALLED!
IN: 44
DESTRUCTOR CALLED!
IN: 45
DESTRUCTOR CALLED!
IN: 46
DESTRUCTOR CALLED!
OUT: 94267720287872 <-- valgrind no likey
IN: 47
DESTRUCTOR CALLED!
IN: 48
DESTRUCTOR CALLED!
IN: 49
DESTRUCTOR CALLED!
IN: 50
DESTRUCTOR CALLED!
IN: 51
DESTRUCTOR CALLED!
IN: 52
DESTRUCTOR CALLED!
OUT: 94267721676608 <-- valgrind sad
OUT: 94267721723376 <-- valgrind is sending me hate mail
... etc ...
```

I'm not sure how I would integrate a test.

**Comment by lu-zero** [comment]
The wip patch should fix it but again, I'd rather have you to test since the testcase I fairly big ^^;

**Comment by dwbuiten** [comment]
Same behavior with new update.

**Comment by lu-zero** [comment]
Found the problem, now the update has a test and some documentation so the user knows who owns the memory in the C-API.

**Comment by lu-zero** [comment]
It is called, I wrote a test to confirm it. (`cargo test --features capi capi --nocapture` to see what is doing).

The Packet does not destroy the pointer on purpose.

**Comment by lu-zero** [comment]
Thank you for checking :)

**Pull request merged**
