### PR TITLE
Unbreak all features test

### LINKED ISSUE #1987: Some doc tests failures in src/api/context.rs
Rust 1.40 on x86_64 with all features enabled:

```
running 6 tests
test src/api/context.rs - api::context::Context<T>::new_frame (line 39) ... ok
test src/api/config.rs - api::config::Config::new_context (line 624) ... ok
test src/api/context.rs - api::context::Context<T>::receive_packet (line 184) ... FAILED
test src/api/context.rs - api::context::Context<T>::receive_packet (line 209) ... FAILED
test src/lib.rs - version (line 163) ... ok
test src/api/context.rs - api::context::Context<T>::send_frame (line 72) ... FAILED

failures:

---- src/api/context.rs - api::context::Context<T>::receive_packet (line 184) stdout ----
Test executable failed (terminated by signal).

---- src/api/context.rs - api::context::Context<T>::receive_packet (line 209) stdout ----
Test executable failed (terminated by signal).

---- src/api/context.rs - api::context::Context<T>::send_frame (line 72) stdout ----
Test executable failed (terminated by signal).


failures:
    src/api/context.rs - api::context::Context<T>::receive_packet (line 184)
    src/api/context.rs - api::context::Context<T>::receive_packet (line 209)
    src/api/context.rs - api::context::Context<T>::send_frame (line 72)

test result: FAILED. 3 passed; 3 failed; 0 ignored; 0 measured; 0 filtered out
```

Even if I ignore the tests, the process segfault: 
`
process didn't exit successfully: `/builddir/build/BUILD/rav1e-0.2.0/target/release/deps/rav1e-390ad111173cb1f6 --skip 'api::context::Context<T>::receive_packet' --skip 'api::context::Context<T>::send_frame'` (signal: 11, SIGSEGV: invalid memory reference)`

```
(lldb) bt
* thread #27, name = 'api::test::flus', stop reason = signal SIGSEGV: invalid address (fault address: 0x10)
    frame #0: 0x00007ffff778fe74 libpthread.so.0`__GI___pthread_mutex_lock + 4
    frame #1: 0x00005555557e8693 rav1e-76cb4f8afe1b5a60`ht_mutex_lock + 19
    frame #2: 0x00005555557e8731 rav1e-76cb4f8afe1b5a60`ht_registry_find_listener_container + 65
    frame #3: 0x00005555557e90c4 rav1e-76cb4f8afe1b5a60`ht_find_or_create_listener + 20
    frame #4: 0x00005555557e8d84 rav1e-76cb4f8afe1b5a60`ht_timeline_create + 84
    frame #5: 0x00005555557e85e8 rav1e-76cb4f8afe1b5a60`ht_global_timeline_get + 88
    frame #6: 0x00005555557e818a rav1e-76cb4f8afe1b5a60`rust_hawktracer_sys::internals::scoped_tracepoint::add_cached_mapping::hb3fff368fcee073f(name="send_frame") at scoped_tracepoint.rs:29:45
    frame #7: 0x0000555555785392 rav1e-76cb4f8afe1b5a60`rav1e::api::internal::ContextInner$LT$T$GT$::send_frame::he7b950c23772c786 + 82
    frame #8: 0x0000555555768075 rav1e-76cb4f8afe1b5a60`rav1e::api::test::flush_unlimited::h34163ce2d2b694eb + 421
    frame #9: 0x00005555557f40bf rav1e-76cb4f8afe1b5a60`_$LT$alloc..boxed..Box$LT$F$GT$$u20$as$u20$core..ops..function..FnOnce$LT$A$GT$$GT$::call_once::hc4e9a5e51ecfbb50 + 63
    frame #10: 0x0000555555846f6a rav1e-76cb4f8afe1b5a60`__rust_maybe_catch_panic + 26
  * frame #11: 0x000055555580e8d5 rav1e-76cb4f8afe1b5a60`test::run_test::run_test_inner::_$u7b$$u7b$closure$u7d$$u7d$::h7297dc3d4dfbd406 + 277
    frame #12: 0x00005555557e9975 rav1e-76cb4f8afe1b5a60`std::sys_common::backtrace::__rust_begin_short_backtrace::hedc93fd720d98d39 + 85
    frame #13: 0x00005555557edb05 rav1e-76cb4f8afe1b5a60`std::panicking::try::do_call::he38648d2de10e061 + 85
    frame #14: 0x0000555555846f6a rav1e-76cb4f8afe1b5a60`__rust_maybe_catch_panic + 26
    frame #15: 0x00005555557ee022 rav1e-76cb4f8afe1b5a60`core::ops::function::FnOnce::call_once$u7b$$u7b$vtable.shim$u7d$$u7d$::h297d3709f1fa9c84 + 194
    frame #16: 0x000055555583991f rav1e-76cb4f8afe1b5a60`_$LT$alloc..boxed..Box$LT$F$GT$$u20$as$u20$core..ops..function..FnOnce$LT$A$GT$$GT$::call_once::h119df384485e079d + 63
    frame #17: 0x0000555555846350 rav1e-76cb4f8afe1b5a60`std::sys::unix::thread::Thread::new::thread_start::ha7e8e0c43366c502 + 144
    frame #18: 0x00007ffff778d4e2 libpthread.so.0`start_thread + 226
    frame #19: 0x00007ffff76a0693 libc.so.6`__GI___clone + 67
```

### PR DESCRIPTION
**Pull request by lu-zero**
Fixes #1987

### CODE REVIEW

**Comment by eclipseo** [comment]
I've tested this locally on rav1e 0.2.0 and src/api/context.rs tests still segfaults when tracing is enabled.

**Comment by lu-zero** [comment]
I would land this and document that using `all-features` in general is discouraged.

**Comment by lu-zero** [comment]
I landed the useful commit on the other PR, this one can be closed pending upstream decision regarding the right `cfg` tag.

**Comment by eclipseo** [comment]
> Agreed, we have some features that don't necessarily play nicely together. Many of our features are specifically for debugging. If you want a fully featured binary, the default feature set gives you that.

Thank you I will listen to that advice.

**Pull request closed without merging**
