### PR TITLE
Enable tx partition depth 2

### PR DESCRIPTION
**Pull request by ycho**
Fix for #1195 and current issue 3 of tiling, https://github.com/xiph/rav1e/pull/1126.

### CODE REVIEW

**Comment by ycho** [comment]
Since this PR has commit which disables directional intra prediction, there will be loss of coding gain as before. With 2n commit applied, i.e. enabling intra tx depth partition depth = 2, there will be small amount of coding gain.

**Comment by ycho** [comment]
By 1st commit,

[AWCY loss of coding gain](https://beta.arewecompressedyet.com/?job=master-5ee66c1c978d2dc25dd16e58f77b74d468dd1b44&job=disable_dir_intra_pred%402019-04-08T23%3A49%3A30.531Z)

|   PSNR | PSNR Cb | PSNR Cr | PSNR HVS |   SSIM | MS SSIM | CIEDE 2000 |
|   ---: |    ---: |    ---: |     ---: |   ---: |    ---: |       ---: |
| 0.5464 |  0.5360 |  0.6911 |   0.5730 | 0.6738 |  0.6032 |     0.4765 |

For -s 3,
[AWCY disabling directional intra prediction](https://beta.arewecompressedyet.com/?job=disable_dir_intra_pred_s3%402019-04-09T01%3A50%3A25.742Z&job=master-8412ff0b_s3%402019-04-08T23%3A50%3A02.127Z)

|   PSNR | PSNR Cb | PSNR Cr | PSNR HVS |   SSIM | MS SSIM | CIEDE 2000 |
|   ---: |    ---: |    ---: |     ---: |   ---: |    ---: |       ---: |
| 0.8206 |  0.7155 |  0.3183 |   0.8639 | 0.9814 |  0.9463 |     0.7791 |

then with 2nd commit, i.e. enabling depth = 2 tx partition,
[AWCY](https://beta.arewecompressedyet.com/?job=disable_dir_intra_pred_s3%402019-04-09T01%3A50%3A25.742Z&job=tx_partition_depth2_with_disabled_dir_intra_pred_s3%402019-04-08T23%3A50%3A35.833Z)

**Comment by lu-zero** [comment]
@ycho might be good to open an issue about the directional predictors.

**Comment by ycho** [comment]
@lu-zero , sure I will create separate issue for the fragile directional intra prediction. Thanks-

**Pull request merged**
