### PR TITLE
Update lv_map for TX64x64.

### PR DESCRIPTION
**Pull request by tdaede**

### CODE REVIEW

**Comment by ycho** [comment]
In addition to this change, enabling 64x64tx size needs recovering all removed entries in several enum and tables which usually has the size TX_SIZES_ALL.

**Comment by ycho** [comment]
https://github.com/xiph/rav1e/pull/231. includes the work here, so I'd close this PR.

**Comment by rzumer** [comment]
I assume that this is outdated, so closing as per @ycho's suggestion.

**Comment by ycho** [comment]
Right, thanks for closing!

**Pull request closed without merging**
