### PR TITLE
Update from copyright headers

### PR DESCRIPTION
**Pull request by darakian**
Simple update to resolve
https://github.com/xiph/rav1e/issues/2516

Generated with
```
sed -i 's/Copyright (c) 2019,/Copyright (c) 2020,/' $(grep 'Copyright \(c\) 2019,' -l)
```

### CODE REVIEW

**Review by vibhoothiiaanand — COMMENTED** [review]
So, in my opinion, we should update headers of files which was having 201X and if they are modified in 2020, to update with 201X-2020 like that, and also see if we are missing any headers on any files.

**Comment by darakian** [comment]
Ok. Easy enough to change :)

I'll modify these to read as `Copyright (c) 2019-2020, ...`. Should I update more than simply the 2019 headers? I assumed that if they were older then there was a reason.

**Comment by vibhoothiiaanand** [comment]
> Ok. Easy enough to change :)
> 
> I'll modify these to read as `Copyright (c) 2019-2020, ...`. Should I update more than simply the 2019 headers? I assumed that if they were older then there was a reason.

Need to see properly, some/many of 2019 files may not be touched in 2020 too, so have to manually check with git blame or something similar to get to know if they are modified.

**Comment by darakian** [comment]
> Need to see properly, some/many of 2019 files may not be touched in 2020 too, so have to manually check with git blame or something similar to get to know if they are modified.

Oh I see. So only the files which were touched should be updated. Ok, give me a bit and I'll update the commit.

**Comment by darakian** [comment]
Ok @vibhoothiiaanand I've updated to only update files touched this year. It looks like all copyrights were either already ranges ending in 2018 or 2019 or were the single year 2019. I've included my scripts in the second and third commits to aid in automating this in the future :)

**Review by lu-zero — APPROVED** [review]
I'm fine with this, @vibhoothiiaanand do you want something more?

**Review by vibhoothiiaanand — APPROVED** [review]
Seems good to me as well, 
We can re-use the scripts, thanks for that, I haven't look closely and overall these seems to be correct.

**Comment by vibhoothiiaanand** [comment]
Thank you for the patchset

**Pull request merged**
