### PR TITLE
Document dependencies required to build rav1e.

### PR DESCRIPTION
**Pull request by tszymczak**
I decided to try out rav1e this weekend. There were dependencies that I needed to install but weren't explained in the documentation. It's a good idea to note that we need these libraries and how to install them.

### CODE REVIEW

**Comment by tdaede** [comment]
Thanks! Yeah, this happens because we now inherit all libaom deps.

**Comment by tszymczak** [comment]
Cool, I'm a contributor now!

**Comment by tdaede** [comment]
Actually did you need to install these deps for "cargo build" to work? I'm trying to drop at least the wx dep.

**Comment by tszymczak** [comment]
My memory is fuzzy now but I think so.

**Pull request merged**
