### PR TITLE
Cdef rdosetup

### PR DESCRIPTION
**Pull request by xiphmont**
Implement all the bitstream infrastructure for full CDEF
Some abstraction setup work to get to the RDO work

### CODE REVIEW

**Comment by xiphmont** [comment]
We could.  Is it superior in any way?

**Comment by lu-zero** [comment]
You won't need explicit lifetimes :)

**Comment by tdaede** [comment]
You could also just do a straight-up copy into the fi. (maybe that's what lu-zero meant, I don't know how just putting two references in a struct would avoid the lifetimes)

**Comment by lu-zero** [comment]
@tdaede exactly.

**Comment by xiphmont** [comment]
...so it should be SequenceInvariants? :-)  It's worth noting the FrameInvariants aren't... they mutate in the course of encoding.

Are folks happy with a copy into fi?  There are two somewhat opposing suggestions here....

**Comment by tdaede** [comment]
This was replaced by montywork right?

**Comment by xiphmont** [comment]
yes.

**Pull request closed without merging**
