### PR TITLE
Stop using Dimension traits for inverse transform

### PR DESCRIPTION
**Pull request by KyleSiefring**

### CODE REVIEW

**Comment by lu-zero** [comment]
What is the impact overall ?

Also we might rediscuss how we dispatch the arch-specific functions sooner or later.

**Comment by KyleSiefring** [comment]
It shaved a few seconds (1% off a clean build) off of compile times and doesn't seem to impact runtime.

**Comment by lu-zero** [comment]
It should reduce the binary size as well.

**Comment by KyleSiefring** [comment]
30.4MB to 29.4MB. not bad.

**Comment by shssoichiro** [comment]
Unrelated to this PR: For release binaries we should run `strip` also. Since we build with debug symbols, that can reduce the binary size by 90%. (Even with default settings for Cargo, strip still gives 50% binary size reduction.)

**Comment by lu-zero** [comment]
I assumed we split the debug information in the action already. I guess might be good to document it.

**Comment by KyleSiefring** [comment]
I went and measured performance without the inverse assembly and there doesn't seem to be a performance impact. I changed the commit message to include this info.

**Comment by lu-zero** [comment]
Thank you :)

**Pull request merged**
