### PR TITLE
Add encode-decode test for various frame dimensions

### PR DESCRIPTION
**Pull request by rzumer**
Only a speed of ~0~ 4 is considered in this test, as ~most desynchronization issues will appear as more options are used during encoding~ speed levels and desynchronization are already tested elsewhere.

### CODE REVIEW

**Comment by rzumer** [comment]
I misunderstood the objective of existing speed and quantizer tests; would testing frame sizes be relevant at a higher speed level?

**Comment by lu-zero** [comment]
Probably this PR could enjoy a rebase

**Comment by rzumer** [comment]
Your commits show up *because* it was rebased.

**Comment by lu-zero** [comment]
After I manually rebased your set in the current master I'm getting this:
```
2018-07-28 15:43 rzumer               o [master] Comment out failing dimensions in decoding test
2018-07-28 10:15 rzumer               o Reduce runtime of dimensions encode-decode test
2018-07-28 10:14 rzumer               o Add testing subsection in README.md
2018-07-28 09:56 rzumer               o Remove redundant .gitignore
2018-07-27 19:19 rzumer               o Add encode-decode test for various frame dimensions
2018-07-27 19:19 rzumer               o Ignore aom.rs in all directories
2018-07-28 14:57 Luca Barbato         o {origin/master} {origin/HEAD} Add the output comparison capability
```

Are you sure you rebased it :) ?

**Comment by ycho** [comment]
I believe we want to squash when landing?

**Comment by rzumer** [comment]
I will favor merging in the future since it seems to be less confusing, and rebasing over a remote branch is considered bad practice apparently. Commits will be squashed either way, so it should make no difference here.

**Comment by lu-zero** [comment]
Merge is quite bisect-unfriendly, you do not want to use it.

**Pull request merged**
