### PR TITLE
Add signal support

### PR DESCRIPTION
**Pull request by lu-zero**
So the cli can exit cleanly on sigterm.

### CODE REVIEW

**Comment by lu-zero** [comment]
there is a [ctrlc](https://crates.io/crates/ctrlc) that could be also used for this purpose.

**Comment by tdaede** [comment]
Looks okay. Does this slow down exiting by a lot?

**Comment by tdaede** [comment]
In particular, it may make sense to not catch the second Ctrl-C.

**Comment by lu-zero** [comment]
It slows down by one frame encoding, I can check if I can refine the behavior

**Comment by tdaede** [comment]
OK. Just turning off the handler after one Ctrl-C would be fine. I just predict it being hugely annoying at -s 0 to wait a minute for the encoder to exit.

**Comment by lu-zero** [comment]
Updated accordingly.

**Pull request merged**
