### PR TITLE
Update libaom

### PR DESCRIPTION
**Pull request by Luni-4**
Libraries are installed correctly, but tests fail.

### CODE REVIEW

**Comment by lu-zero** [comment]
You must update the aom-sys crate to 2.0.

**Comment by lu-zero** [comment]
https://github.com/xiph/rav1e/pull/2415 should go in first.

**Comment by Luni-4** [comment]
> #2415 should go in first.

Ouch, I forgot to add that! Yep, it should go in first

**Comment by Luni-4** [comment]
@lu-zero 

It doesn't work the same

**Comment by Luni-4** [comment]
Close in favor of #2323

**Pull request closed without merging**
