### PR TITLE
AppVeyor: Don't run on non-essential code changes

### PR DESCRIPTION
**Pull request by EwoutH**
Don't let AppVeyor run on documentation changes, CI changes, etc.

### CODE REVIEW

**Comment by lu-zero** [comment]
Looks good to me.

**Comment by lu-zero** [comment]
Please rebase

**Comment by EwoutH** [comment]
Thanks! Can't rebase, branch is up to date.

**Comment by EwoutH** [comment]
@lu-zero Rebased now I've got something to rebase on :)

**Comment by lu-zero** [comment]
Thank you!

**Pull request merged**
