### PR TITLE
Maybe a new crates.io release?

### PR DESCRIPTION
**Pull request by kornelski**
There are significant unreleased quality/performance improvements. 

BTW: rav1e has a very long release cycle, IMHO way too slow for the pace of changes in rav1e and around AV1 in general. 

The long release cycle paradoxically makes stable versions of rav1e quite unattractive. The latest not-alpha v0.4 is too far behind in performance/quality to be useful. Currently only the unreleased version of rav1e is competitive with libaom for AVIF compression.

### CODE REVIEW

**Comment by lu-zero** [comment]
I think we could consider stable the new API and get the 0.5 out. We should discuss it the next meeting, but I was already planning to cut a beta next week.

**Comment by shssoichiro** [comment]
I'm also +1 for more frequent point releases. In fact, I might say that we should replace the weekly pre-releases with official point releases including a push to crates.io.

**Comment by lu-zero** [comment]
Ideally we do not have further breaking changes so we could push to crates.io point releases nearly from master. The `unstable` feature would shield users from experiments.

**Comment by cryptomilk** [comment]
I would expect a bugfix release for issues like #2662 being fixed. However I will patch packages in openSUSE and Fedora for now.

It might be a good idea to establish a fixed release cycle. For Samba we are doing well with 6 month, same for darktable.

**Comment by tdaede** [comment]
Now that our API is more stable I think a fixed release cycle is a great idea.

One thing I'd really love to have is a more in-depth test specifically to run on releases to avoid any sort of quality regressions - this would be the distinguishing feature between releases and the weekly builds. I don't think that should block 0.5, but I have some plans for the future.

**Comment by eclipseo** [comment]
I too would welcome a new release, not an alpha one, but a proper one, if it's stable enough. I haven't pushed the 0.5 alpha to Fedora because of this, but the significant gains are so useful.

**Comment by lu-zero** [comment]
We plan to land two features and close 0.5 between this week and the next one. @kornelski I drafted the support for the early exit so you can poke at it and tell me what you think and what you'd like to get as progress data btw.

**Comment by kornelski** [comment]
I don't want any new features. There's a serious encoding bug in the 0.5, so I'd like any release of anything, right now. Features can wait.

**Comment by barrbrain** [comment]
[0.5.0-beta](https://crates.io/crates/rav1e/0.5.0-beta) is now available on crates.io as a prerelease.
This should aid wider testing as we finalise 0.5.

**Comment by tdaede** [comment]
I opened #2777 to set up time-based releases for 0.5.1 and onward.

**Pull request closed without merging**
