### PR TITLE
The rdo_mode_decision() only  returns RDOPartitionOutput struct

### PR DESCRIPTION
**Pull request by ycho**
This also makes it possiblt to remove all .clone() calls to
the return value of rdo_mode_decision().

### CODE REVIEW

**Comment by ycho** [comment]
@rzumer, Erk, it got slower for -s 3.
@lu_zero, can you explain why?! :)

**Comment by ycho** [comment]
With -s 1, at some QIndex (including the smallest one, 80), it very^100 slightly reduces the encoding time.

**Comment by tdaede** [comment]
How small of changes are you trying to measure with AWCY here? If it's less than 5% then it's probably not accurate.

**Comment by ycho** [comment]
There you go, I believe it was less than 0.5%! :)

**Comment by tdaede** [comment]
Regardless of speed, this looks way cleaner.

**Comment by ycho** [comment]
@tdaede, thanks for +1!

**Comment by ycho** [comment]
@rzumer? Further comments?

**Pull request merged**
