### PR TITLE
Don't init memory for iimgs in sgr

### PR DESCRIPTION
**Pull request by KyleSiefring**

### CODE REVIEW

**Comment by lu-zero** [comment]
What speedup does it give? You might want to use `MaybeUninit::uninit().assume_init()`

**Comment by KyleSiefring** [comment]
It's about 2.5% faster.

**Comment by KyleSiefring** [comment]
```
  PSNR | PSNR Cb | PSNR Cr | PSNR HVS |   SSIM | MS SSIM | CIEDE 2000
0.0000 |  0.0000 |  0.0000 |   0.0000 | 0.0000 |  0.0000 |     0.0000
```

**Comment by KyleSiefring** [comment]
The new way of getting uninitialized memory is unstable in the version ci is using.

**Comment by rzumer** [comment]
There is another PR (#1359) that includes that change, so I suggest fixing the CI issue on that end instead.

**Pull request merged**
