### PR TITLE
Cpu feature level rework

### PR DESCRIPTION
**Pull request by lu-zero**
- [x] Use Default
- [x] Hide completely the cpu feature from the API
   - [x] Move the field in FrameInvariants

(as discussed with Tim on IRC)

### CODE REVIEW

**Comment by KyleSiefring** [comment]
I suggest you discuss this change with derf, since he is the one who mentioned using environmental variables in theora. I'm not entirely opposed to this change since it makes it possible to use with AWCY, but I don't actually want to average user to have access to this function.

One concern I have is with the ABI. In the future, we want to be able to add and remove different cpu feature levels. Will there be breakage if we do this?

**Comment by lu-zero** [comment]
> I suggest you discuss this change with derf, since he is the one who mentioned using environmental variables in theora. I'm not entirely opposed to this change since it makes it possible to use with AWCY, but I don't actually want to average user to have access to this function.

Currently we have a situation in which the env approach seems to not work and we want the user to report back if something works or not with avx2 turned off.

Not sure which is the function you are wary of.

> One concern I have is with the ABI. In the future, we want to be able to add and remove different cpu feature levels. Will there be breakage if we do this?

Until we have dynamic libraries, our concern is on the API stability :)

If you want to mix and match multiple implementations at runtime then we'd either have to extend the enum with all the supported combinations or we'd have to use a struct of booleans.

In general I guess I'll have to discuss with Tim a lot since if we want to do that it would mean multiple branches in hot paths and that feels more problematic that what is already present.

**Comment by moisesmcardona** [comment]
Unfortunately, it seems to not be helping. Both Native and AVX2 fails.

image

**Comment by lu-zero** [comment]
> I suggest you discuss this change with derf, since he is the one who mentioned using environmental variables in theora. I'm not entirely opposed to this change since it makes it possible to use with AWCY, but I don't actually want to average user to have access to this function.

Derf wants to have a debug-only facility so I removed it from the API completely.

**Pull request merged**
