### PR TITLE
Make it easier for cdef dist to auto-vectorize

### PR DESCRIPTION
**Pull request by KyleSiefring**
Cdef dist should autovectorize with default compiler flags now.

Since I don't see a performance benifit from it anymore, remove the forced
inlining.

### CODE REVIEW

**Comment by lu-zero** [comment]
If you enable avx2 what does it happen?

**Comment by KyleSiefring** [comment]
Honestly, I couldn't seem to get any vectorized code on master with RUSTFLAGS="-C target-feature=+avx2,+fma". When I tested removing the inlining, I ran with those options. I was thinking of leaving it in if there were speedups with avx2.

**Comment by shssoichiro** [comment]
Looks [optimized and unrolled](https://pastebin.com/v8UEVq4N) although only using SSE2 opts even with AVX2 enabled, but our microbenchmark on my machine shows that this version is 20% slower.

**Comment by KyleSiefring** [comment]
I ran the microbenchmarks and did reproduce the a performance regression, but in the order of a couple percent instead.

Here are the awcy results. I do see performance improvements here.
https://beta.arewecompressedyet.com/?job=master-0a1335fb86686808df86654938fae420c77b4660&job=auto_vec_cdef_dist_2%402019-12-27T17%3A23%3A29.539Z

I guess more investigation is warranted.

**Comment by shssoichiro** [comment]
I wonder if it depends on CPU architecture. My current machine is running an i7-6700.

**Comment by KyleSiefring** [comment]
Try it now.

**Comment by shssoichiro** [comment]
This version is 50% faster compared to master, strangely enough. Running a full encode, 1080p ducks take off, encode speed is about 3% faster at speed 6.

**Pull request merged**
