### PR TITLE
Move the decode test to aom-sys

### PR DESCRIPTION
**Pull request by lu-zero**

### CODE REVIEW

**Comment by tdaede** [comment]
Can this now drop the submodule too?

**Comment by lu-zero** [comment]
We have a benchmark and a test that depends on it, we could remove the submodule and that code.

**Comment by tdaede** [comment]
OK. Regardless this looks fine, as long as the decode test is just as easy to run. Just installing libaom system wide makes it work, correct?

**Comment by lu-zero** [comment]
Correct

**Pull request merged**
