### PR TITLE
[WIP] Enable 64x64 tx

### PR DESCRIPTION
**Pull request by ycho**
Need to further work. Since there are issues with h_pred and v_pred with 64x64 tx. dc_pred is fine.

Also, RDO block side decision is temporarily disabled for testing.

### CODE REVIEW

**Comment by tdaede** [comment]
Do the other predictors like smooth / paeth work?

**Comment by ycho** [comment]
No, it works for DC_PRED only.
For other new predictors paeth or smooth(?), I believe they are not even tested on master yet?
Chagall can confirm?

**Comment by ycho** [comment]
Also, I've got some rust compile errors on Travis due to new exported tx functions from libaom.

**Comment by fbossen** [comment]
Is further work on this planned?

**Comment by ycho** [comment]
Yes, it sure will, talked about that with Tim while ago.

**Comment by rzumer** [comment]
Superseded by #711.

**Pull request closed without merging**
