### PR TITLE
Update the y4m dependency

### LINKED ISSUE #1983: Improve error message when feeding a non-y4m input
Currently rav1e gives this:
````
The application panicked (crashed).
  cannot decode the input: ParseError
in src/libcore/result.rs, line 1165
thread: main
````

### PR DESCRIPTION
**Pull request by rzumer**
This closes #1983.

### CODE REVIEW

**Comment by lu-zero** [comment]
Looks like the error type changed.

**Comment by rzumer** [comment]
Fixed the error type mapping, but now there are many errors because of https://github.com/image-rs/y4m/commit/9f25fd03a43ed4ba086f3a7cc793b24fb796b354 that I don't want to deal with right now.

**Comment by lu-zero** [comment]
Should be is just removing `'_,` in 3 places.

**Comment by rzumer** [comment]
I'd pushed my last change to my fork instead of here, but as you can see that's nowhere near enough.

**Comment by lu-zero** [comment]
Almost, you need to rebase to the current master and add 
https://github.com/rust-av/rav1e/commit/8c5d6091a9bae2589f256820b4607900e9a87322

Since you the y4m let you store the Write/Read directly in the struct, you have to remove some &/&mut around the constructors.

**Comment by rzumer** [comment]
Thanks, often seems like Rust error messages are an unreadable mess even when the fix is simple.

**Comment by lu-zero** [comment]
They were swamped in the errors uncovered by the paste update. After the rebase they were much simpler to follow :)

**Pull request merged**
