### PR TITLE
Change min block size for speed 1 from 8x8 to 4x4

### PR DESCRIPTION
**Pull request by ycho**
[AWCY results showing the change from master at speed 1](https://beta.arewecompressedyet.com/?job=master-2b20894d_s1%402019-08-21T16%3A10%3A31.334Z&job=test_s1_min_blk_4x4%402019-08-21T16%3A17%3A33.625Z)

### CODE REVIEW

**Comment by shssoichiro** [comment]
I find the AWCY results very surprising. I wouldn't expect BD Rate decreases from enabling 4x4 under any ccircumstances.

**Comment by ycho** [comment]
> I find the AWCY results very surprising. I wouldn't expect BD Rate decreases from enabling 4x4 under any circumstances.

Indeed, I've just seen that right before your message and was checking the bitstream locally and found that there is DCT tx only!

**Comment by ycho** [comment]
[awcy at speed 1, psnr](https://beta.arewecompressedyet.com/?job=min_blk_size4x4-s1_psnr%402019-09-18T17%3A49%3A48.142Z&job=master-13222dd-s1_psnr%402019-09-18T17%3A49%3A31.630Z)


|    PSNR | PSNR Cb | PSNR Cr | PSNR HVS |    SSIM | MS SSIM | CIEDE 2000 |
|    ---: |    ---: |    ---: |     ---: |    ---: |    ---: |       ---: |
| -0.8631 |  0.8349 |  1.0557 |  -0.5717 | -0.6378 | -0.4993 |    -0.4373 |

**Comment by ycho** [comment]
As experiment to show that tx partitions of 4x4 (with min blk size = 8x8) lessens the effect of changing to min blk size 4x4, if tx size rdo is off, there is slightly more gain like 0.1%.

[awcy at speed 1, min blk size 8x8 -> 4x4, psnr, with tx size rdo off(https://beta.arewecompressedyet.com/?job=master-13222dd_off_tx_size_rdo_s1_psnr%402019-09-18T17%3A50%3A04.474Z&job=min_blk_size4x4_off_tx_size_rdo-s1%402019-09-18T17%3A46%3A39.593Z)

**Comment by ycho** [comment]
@tdaede, sorry- pressed the button by curiosity, and knew that it was for 're-request a review'!

**Pull request merged**
