### PR TITLE
Add intra inter mode coding

### PR DESCRIPTION
**Pull request by ycho**
For #160.

- Add inter/intra mode symbol for blocks in inter frame.
- Add intra prediction mode coding for inter frame.

### CODE REVIEW

**Comment by ycho** [comment]
Since I moved to Level Map coding, I wanted to finish what I have worked for enabling basic intra mode coding so far and committed two required patches for inter mode.

**Comment by tdaede** [comment]
Cool. You need to push your libaom changes.

**Comment by ycho** [comment]
tdaede: Do I have to commit libaom changes separately (I did that way before)?
If so, should I commit it to your github libaom branch only (i.e. https://github.com/tdaede/aom) ? or any branch in git?
Once libaom is commited then I need to update (commit & push -f) my rav1e commits as well, correct?

**Comment by tdaede** [comment]
You can just push it to the rav1e_10 branch on my aom, but any public branch will work.

You'll need to update your rav1e commits too, but if the hash didn't change it might not see any changes - let me know and I'll manually retrigger travis.

**Comment by ycho** [comment]
The existing 'show-existing-frame logic ' should behave independently, so every even odd numbered should not be encoded as before, but show previously encoded frame. 
Ex, frame 0 encoded, frame 1 (INTER frame) NOT encoded, ....

**Comment by ycho** [comment]
I think better way to monitor 'show-existing-frame flag' is to output it thru eprintln!("{}", fi); in process_frame(), which shows current frame # and intra/inter frame.

**Comment by tdaede** [comment]
In fact now that we have "real inter" frames we can probably stop using show-existing-frames for now. We'll need them when we do out-of-order but that's for later.

**Pull request merged**
