### PR TITLE
Add configuration for grcov action

### PR DESCRIPTION
**Pull request by barrbrain**
Remove some noise in results reported on Coveralls. Effectively limit results to the rav1e crate sources.

### CODE REVIEW

**Comment by lu-zero** [comment]
Sounds good

**Comment by barrbrain** [comment]
Compare the result from [this PR](https://coveralls.io/builds/27453288) with [master](https://coveralls.io/builds/27436556):
* `../`
* `crates/`
* `ivf/`

**Comment by shssoichiro** [comment]
We should probably also ignore src/test_encode_decode

**Comment by barrbrain** [comment]
> We should probably also ignore src/test_encode_decode

Perhaps, I think that is part of a wider conversation about rationalising our test coverage.
The primary intent of this PR was reduce the noise from Coveralls.

**Pull request merged**
