### PR TITLE
CI: Always use latest cargo-c and grcov versions

### PR DESCRIPTION
**Pull request by EwoutH**
Prevents having to update it manually all the time

### CODE REVIEW

**Comment by tmatth** [comment]
On one hand this would make CI builds arguably less reproducible, on the other hand I'm assuming it would log whatever version was used so maybe it's not such a bad tradeoff.

**Comment by EwoutH** [comment]
That's indeed the trade-off. On the macOS builds we install cargo-c using homebrew by the way, which also picks the latest version.

@lu-zero Could you tell me a bit about the changed package names between cargo-c [v0.9.4](https://github.com/lu-zero/cargo-c/releases/tag/v0.9.4) and [v0.9.5](https://github.com/lu-zero/cargo-c/releases/tag/v0.9.5)? Noticed they are different, for example, the linux version is now a .zip instead a .tar.gz, and couldn't find anything in the release notes or commits.

**Comment by lu-zero** [comment]
The deploy script failed also on cargo-c so it is a manual recover, please open an issue about it and I'll fix it tomorrow.

**Comment by EwoutH** [comment]
Thanks for getting back so quickly! Opened an issue: https://github.com/lu-zero/cargo-c/issues/235

**Comment by lu-zero** [comment]
Now it should be fixed, please try again.

**Comment by EwoutH** [comment]
Thanks! I removed by last commit and rebased, and it looks like the cargo-c builds now pass.

**Comment by lu-zero** [comment]
It needs a second rebase, I'll land it after.

**Review by lu-zero — APPROVED** [review]

**Pull request merged**
