### PR TITLE
Implement segmentation

### PR DESCRIPTION
**Pull request by atomnuker**
Only works for now on keyframes and as long as the delta does not have to make the quantization cdfs change index.

### CODE REVIEW

**Comment by tdaede** [comment]
Looks fine, but how you are testing this?

**Comment by atomnuker** [comment]
By setting fs.segmentation.features[0][SegLvl::SEG_LVL_ALT_Q as usize] = true; and adjusting the delta, of course.
Ready for merging, does not desync on inter frames anymore.

**Comment by tdaede** [comment]
Needs rebase

**Comment by tdaede** [comment]
I'd like more encode decode tests for this, but given how long this has been open, I think we should land it now.

**Pull request merged**
