### PR TITLE
[WIP] Select a reasonable MV predictor from MVs in stack

### PR DESCRIPTION
**Pull request by fbossen**
Select the MV predictor with the smallest L1 distance from the
MV to be coded

### CODE REVIEW

**Comment by fbossen** [comment]
This isn't working terribly well at the moment:

|    PSNR | PSNR Cb | PSNR Cr | PSNR HVS |    SSIM | MS SSIM | CIEDE 2000 |
|    ---: |    ---: |    ---: |     ---: |    ---: |    ---: |       ---: |
| -0.1738 | -0.2379 | -0.2976 |  -0.1795 | -0.1365 | -0.1248 |    -0.2665 |

**Comment by tdaede** [comment]
I don't think this ever gave big gains in libaom either, assuming that whatever you were coding before was relatively sane.

**Comment by ycho** [comment]
The description of this PR needs be updated since the code now considers logarithmic distance of MV in each dimension, which is far closer to actual bit rates than linear L1 distance.

**Comment by fbossen** [comment]
This isn't getting better

|    PSNR | PSNR Cb | PSNR Cr | PSNR HVS |    SSIM | MS SSIM | CIEDE 2000 |
|    ---: |    ---: |    ---: |     ---: |    ---: |    ---: |       ---: |
| -0.0636 | -0.1560 | -0.1680 |  -0.0585 | -0.0120 | -0.0445 |    -0.0648 |

**Comment by ycho** [comment]
Wouldn't it because MV cost is still negligible ? I.e. search range is not large yet....*_*

**Comment by fbossen** [comment]
@ycho I should probably try lower speed settings. More bits should be spent on MVs when blocks are smaller

**Comment by ycho** [comment]
Also, is mv_cost included in final rd_cost used by bottom_up and top_down partition search? I think last time your fixed that partitioning cost be included.

**Comment by rzumer** [comment]
Since it is unlikely that this PR will be revived any time soon, I will close it now as suggested.

**Pull request closed without merging**
