### PR TITLE
Change MV mode if NEAREST isn't NEAREST anymore

### PR DESCRIPTION
**Pull request by fbossen**

### CODE REVIEW

**Comment by fbossen** [comment]
Addresses same issue as #532 but without speed penalty. RD penalty to be determined

**Comment by fbossen** [comment]
|   PSNR | PSNR Cb | PSNR Cr | PSNR HVS |   SSIM | MS SSIM | CIEDE 2000 |
|   ---: |    ---: |    ---: |     ---: |   ---: |    ---: |       ---: |
| 1.8231 |  1.5903 |  2.0027 |   1.8724 | 1.8174 |  1.8226 |     1.7642 |

**Comment by ycho** [comment]
Is above awcy results saying rergession? 
Otherwise,  just the comparison direction is this patch --> ref, and an improvement?

**Comment by fbossen** [comment]
yes, it's an RD regression wrt to master at speed 1. But it runs 20-25% faster

**Pull request merged**
