### PR TITLE
Fix unnecessary auto-vectorization in residual loop of SAD intrinsics

### PR DESCRIPTION
**Pull request by redzic**
There is no way to force the compiler to not auto-vectorize a loop without changing the global compilation flags. However, it is possible with inline assembly which was stabilized in Rust 1.59.0.

Before, the compiler aggressively vectorized a loop that was supposed to be scalar since it was only a residual loop of an already vectorized function. With this PR, the correct assembly code is generated: https://godbolt.org/z/e6KTfqnxG

### CODE REVIEW

**Comment by tdaede** [comment]
Interesting technique.

There is a lot of potential stuff to evaluate with the addition of inline assembly. One thing that comes to mind is the update_cdf function which has improved assembly in dav1d compared to our intrinsics (in theory).

**Comment by shssoichiro** [comment]
Test failures are from the new clippy warnings in rustc stable. We'll have to do the typical clippy fixup PR.

**Comment by shssoichiro** [comment]
you can rebase now to fix the CI

**Comment by redzic** [comment]
@shssoichiro should be good to go, rebased the PR

**Comment by shssoichiro** [comment]
Since this brings in inline asm, you'll also need to bump the minimum rustc version to 1.59. (We have a few places that do this e.g. build.rs, CI files, maybe a few others)

**Comment by redzic** [comment]
@shssoichiro sorry about that, everything should be fixed now

**Review by shssoichiro — APPROVED** [review]
Thanks!

**Pull request merged**
