### PR TITLE
Fix cli confusing error message

### PR DESCRIPTION
**Pull request by Mesteery**
Fixes: #2543

### CODE REVIEW

**Comment by quietvoid** [comment]
One thing I have noticed is that this error also happens when using stdin as input, and the file needing to be overwritten.
In those cases the use of `-y` is necessary.

**Review by lu-zero — APPROVED** [review]

**Comment by lu-zero** [comment]
Thank you for the patch :)

**Comment by lu-zero** [comment]
Please run rustfmt

**Comment by lu-zero** [comment]
It apparently needs a manual rebase, once you do I'd land it on both `0.5` and `master`.

**Comment by lu-zero** [comment]
github today seems to be particularly annoying, try to run again `git pull --rebase origin && git push {your-repo}` =/

**Pull request merged**
