### PR TITLE
CI: Add a way to skip CI

### PR DESCRIPTION
**Pull request by Luni-4**
This PR skips a CI check when a commit message contains the `[skip ci]` tag.

Thanks in advance for your review! :)

### CODE REVIEW

**Comment by vibhoothiiaanand** [comment]
I wonder why do we need such thing ?

**Comment by tmatth** [comment]
> I wonder why do we need such thing ?

To save time/CO2 if CI isn't required (WIPs, etc.)

**Comment by Luni-4** [comment]
> > I wonder why do we need such thing ?
> 
> To save time/CO2 if CI isn't required (WIPs, etc.)

Yep, exactly

**Review by lu-zero — CHANGES_REQUESTED** [review]
I'd rather use the pull request tags instead.

**Comment by Luni-4** [comment]
> I'd rather use the pull request tags instead.

Good idea! I will implement that then, thanks!

**Comment by Luni-4** [comment]
@lu-zero 

Now it works both with `push` and `pull_request` events. [Here](https://github.com/Luni-4/rav1e/commit/8bec2b7d2d2f22b2cb738eb39e0aa225c3f2912c) you can find a typical commit message that could be used, in this way we don't ruin our history.

**Review by vibhoothiiaanand — APPROVED** [review]
I think this should implement what @lu-zero advised,

**Review by lu-zero — APPROVED** [review]
Would be nicer with the in-commit message as `ci: skip` (since some viewer render `key: value` in git commits)

```
Commit subject

This is the commit body
with 
CI: skip
Co-Autored-by: somebody
...
```

**Comment by Luni-4** [comment]
@lu-zero 

Done

**Review by vibhoothiiaanand — APPROVED** [review]
LGTM :)

**Pull request merged**
