### PR TITLE
Add basic 1-pass rate control

### PR DESCRIPTION
**Pull request by barrbrain**
This is an adaptation of [tterribe/rate_control8](https://git.xiph.org/?p=users/tterribe/rav1e.git;a=shortlog;h=refs/heads/rate_control8):

> This is just the minimal patch required to get something working. There are still plenty of TODOs left to do: two-pass support, VFR support, golden frame support, the ability to drop frames, trial encodes for the first frames, quantization matrices, separate quantizer choices for Cb and Cr, proper lossless handling, support for AV1's levels, and some general refactoring to improve maintainability.

### CODE REVIEW

**Comment by barrbrain** [comment]
Preserved Tim's style for new code in `src/rate.rs` and matched style with the local context otherwise.

**Comment by lu-zero** [comment]
Please rebase it.

**Comment by barrbrain** [comment]
With the encode-decode test, [coverage for rate.rs](https://coveralls.io/builds/21710569/source?filename=src%2Frate.rs) is pretty good. Could possible pick levels carefully to hit more blocks.
**234** of **286** new or added lines in **5** files covered. **(81.82%)**

**Comment by lu-zero** [comment]
I'd merge it now and refine later :)

**Pull request merged**
