### PR TITLE
Ensure that min and max quantizer are respected

### PR DESCRIPTION
**Pull request by shssoichiro**
When specifying e.g. `--bitrate 10000 --min-quantizer 100`, the min-quantizer setting did not appear to take effect. For example, on a test clip of BBB 720p first 500 frames, the average QPs were 20 and 68 for I and P frames respectively. After this PR, the QPs are flat as would be expected of a `--quantizer 100` encode (since bitrate 10000 would, in this case, always want a lower quantizer).

### CODE REVIEW

**Comment by barrbrain** [comment]
This does ensure that min/max quantizer are hard limits. Considering that the same parameters are used to set the bounds of the rate-control search, the cases where they are not respected should be interesting. I need to read through again to understand clearly.

**Comment by lu-zero** [comment]
Maybe we should put an integration test for them.

**Comment by shssoichiro** [comment]
@lu-zero I added some tests to verify this

**Review by lu-zero — APPROVED** [review]
It seems fine to me.

**Comment by shssoichiro** [comment]
Summary of conversation with Tim on IRC:

This is fine as a baseline for now. We want to add to this later to include things like temporal RDO into the calculation. This can probably be done without majorly changing the approach here.

**Pull request merged**
