### PR TITLE
Expand on how to install the library

### PR DESCRIPTION
**Pull request by lu-zero**
Suggest to use `--destdir` and then `sudo cp` the files.

See: #2928

### CODE REVIEW

**Comment by tdaede** [comment]
Should probably use the `install` binary rather than cp to get proper permissions set.

There's also an incantation of cargo cinstall that I managed to install directly with, I can try to find it.

**Comment by lu-zero** [comment]
cargo cinstall does not know about permission, I might add yet another feature to deal with that maybe.

**Comment by lu-zero** [comment]
If you have ready the install command I can add it as well.

**Comment by lu-zero** [comment]
It should be otherwise covered

**Pull request closed without merging**
