### PR TITLE
Rename color config enum variants to match the AV1 specification

### PR DESCRIPTION
**Pull request by rzumer**

### CODE REVIEW

**Comment by lu-zero** [comment]
Adding variants mapping requires to manually implement `FromStr`. I'd argue that the original names for the matrix coeffs are less confusing.

What about adding compat matches in the FromStr instead?

**Comment by rzumer** [comment]
I actually find the current variants to be more confusing. The references listed in the comments/docs do not even use the same naming scheme for some of them, e.g. variants 11 and 12 of primaries. In addition some variants are named according to their SMPTE standard number, while others that have SMPTE names used in the AV1 spec/H.273 are renamed to something else. It is inconsistent. At least with the ffmpeg convention, there is some consistency with a reference.

I would rather keep further improvements like mapping from multiple alternatives to a different PR.

**Comment by lu-zero** [comment]
I'd just follow the AV1 specification names assuming we can map it so they are sane enum values.

You already did the work documenting them so adding an extended FromStr could be an option (probably the macro in use could be extended so aliases are supported as custom `#[arg_alias("", "", "")]`)

**Comment by rzumer** [comment]
I am definitely not against using the AV1 spec names instead, though I think some prefer the ffmpeg conventions. Awaiting comments from the other requested reviewers...

**Comment by dwbuiten** [comment]
I agree with @lu-zero - we should follow the AV1 spec names.

**Comment by rzumer** [comment]
It has matched the spec for 4 days now.

**Comment by sdroege** [comment]
See also https://github.com/xiph/rav1e/issues/1315 . Thanks for taking care of this!

**Pull request merged**
