### PR TITLE
Small ME refactors/improvements

### PR DESCRIPTION
**Pull request by YaLTeR**
[AWCY](https://beta.arewecompressedyet.com/?job=master-599e3dd02a63dcadab3c14482704a4074e6fe92a&job=fix-me-probably-2019-08-08_132638-02d2b27)

### CODE REVIEW

**Comment by tdaede** [comment]
Given it's a non-zero AWCY change, which of these is intended to have the change? I would be better to provide the AWCY results in the commit message of that particular commit.

**Comment by YaLTeR** [comment]
f89a858 might or might not change AWCY results depending on how the motion search works, and 
02d2b27 changes AWCY

**Comment by tdaede** [comment]
You should run just f89a858 on AWCY then, and put that result in its commit also.

**Comment by YaLTeR** [comment]
Added those to the commit messages.

**Comment by tdaede** [comment]
Thanks. (Please squash the Clippy fix)

**Comment by YaLTeR** [comment]
:white_check_mark:

**Pull request merged**
