### PR TITLE
Add aarch64 NEON 8-bit SATD assembly for 4x4-transformed block sizes

### PR DESCRIPTION
**Pull request by redzic**
This PR only adds assembly for block sizes that use a 4x4 transform for now.

### CODE REVIEW

**Comment by redzic** [comment]
I only have access to my M1 for the time being, so my other PR for adding avx2 hbd satd assembly will be a bit delayed

**Review by vibhoothi — COMMENTED** [review]
Nice, would be nice to see any numbers showing the impact of the code^^

**Comment by redzic** [comment]
I'll try to do actual benchmarking later, but some initial testing suggests around a ~2-3% overall reduction in encoding time (tested on speed 2, 4 tiles, 4:2:0 1080p on an M1 pro). This only affects speed <= 2 in practice, I guess because faster presets don't search small block sizes.

Hopefully once I add assembly for 8x8 transform-based blocks in another PR, the speedup will be higher.

**Review by lu-zero — APPROVED** [review]
I guess it could land as-is or you'd rather wait?

**Review by barrbrain — CHANGES_REQUESTED** [review]
This doesn't compile with my aarch64 clang unless I change the comment format.
```
Alpine clang version 13.0.1
Target: aarch64-alpine-linux-musl
Thread model: posix
InstalledDir: /usr/bin
```
It doesn't compile at all with gcc even after fixing the comment format.
```
localhost:~/rav1e$ gcc --version                                                gcc (Alpine 11.2.1_git20220219) 11.2.1 20220219
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
The test fails on my device:
```
failures:

---- dist::test::get_satd_same_u8 stdout ----
thread 'dist::test::get_satd_same_u8' panicked at 'assertion failed: `(left == right)`

Diff < left / right > :
<1408
>1662

', src/dist.rs:507:7
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    dist::test::get_satd_same_u8

test result: FAILED. 219 passed; 1 failed; 24 ignored; 0 measured; 0 filtered out; finished in 8.33s
```

**Comment by redzic** [comment]
The tests were failing because I used src_stride for dst in some places, and the tests actually tested when the 2 planes had different strides. Fixed now.

@barrbrain do you know what would be required to fix compilation with gcc? and is there a way to test gcc compilation on macos?

**Comment by barrbrain** [comment]
> @barrbrain do you know what would be required to fix compilation with gcc? and is there a way to test gcc compilation on macos?

I found that I had to set `CFLAGS=-m64` with GCC as the default compiler in my environment.

**Review by barrbrain — APPROVED** [review]
This passes tests for me now with `CC=clang`. I will look into GCC issues in my environment.

**Pull request merged**
