### PR TITLE
update_cdf() for LV_MAP_MULTI=1

### PR DESCRIPTION
**Pull request by ycho**
For #106.
This patch requires corresponding change in libaom,
https://github.com/tdaede/aom/pull/7.

### CODE REVIEW

**Comment by tdaede** [comment]
The git submodule hash needs to be changed to de00675f5021a73257ddaf49048969c55a5c74a0, can you push an update?

**Comment by ycho** [comment]
I think it should be 6844d18? Which is already there? Otherwise, Travis failed it?

**Comment by ycho** [comment]
But any way let me push -f again with libaom set as 6844d18 again.

**Comment by tdaede** [comment]
The problem is what when I click the "Rebase and merge" button in the aom repo on Github, it changes the public git commit hash. So the final one in the aom repo is de00675f50

**Comment by ycho** [comment]
Oh, you are right.
It should point to your rav1e_11, de00675f5021a73257ddaf49048969c55a5c74a0, not mine.

**Comment by ycho** [comment]
I hope this can be more easier than now....

**Pull request merged**
