### PR TITLE
Encode decode tests

### LINKED ISSUE #3: Add a mode to test encode/decode mismatch
Probably by relying on aomdec being on the PATH

### PR DESCRIPTION
**Pull request by lu-zero**
Here the initial implementation of two encode-decode test.
It cover all the speeds and some quantization.
- [x] Encodes random frame data
- [x] Decodes successfully the produced packet
- [x] Decodes unsuccessfully the produced packets
- [x] Detects packet corruption

In the process of using the test, I found the hard way a couple of issues that got fixed in the first commits.

Fixes #3

### CODE REVIEW

**Comment by tdaede** [comment]
It looks like the encode/decode test isn't actually running on Travis.

**Comment by lu-zero** [comment]
we need to decide which one to run and how often, the speed test takes a
lot of time they are behind a feature and disabled by default.

**Comment by tdaede** [comment]
Well, I want at least a basic reconstruction test on Travis... it can run on a non-default speedlevel, I guess.

**Comment by lu-zero** [comment]
Ok, let me add that.

**Pull request merged**
