### PR TITLE
Bump dependencies that rely on old syn version

### PR DESCRIPTION
**Pull request by shssoichiro**
Syn is our slowest-compiling dependency, so we would like
to avoid compiling two versions of it. We still have an old
version of bindgen used by aom-sys and avformat-sys which uses
old syn, but this moves us closer to compiling syn only once.

The new arrayvec also comes with some performance improvements
of its own.

### CODE REVIEW

**Comment by shssoichiro** [comment]
Is someone in the org able to publish a new version of aom-sys? The dependency bump we need is in master of that repo, but hasn't been published to crates.io. If we can get that, I can update avformat-sys as well and we can get off of syn 0.x completely and shave a minute off of build times.

**Comment by lu-zero** [comment]
On it, meanwhile we should land the cargo-c workaround.

**Comment by shssoichiro** [comment]
Going to go all-in and clear out all the syn 0.x dependencies. Just waiting on https://github.com/rust-num/num-derive/issues/32 now.

**Comment by shssoichiro** [comment]
Let it be done.

```
➜ rg 'syn 0' Cargo.lock | wc -l
0
```

**Comment by shssoichiro** [comment]
This actually cut a full 28% off the release build on my machine (360s -> 260s)

**Pull request merged**
