### PR TITLE
Should not save/restore all the block contexts in frame! #124

### PR DESCRIPTION
**Pull request by xiphmont**

### CODE REVIEW

**Comment by lu-zero** [comment]
I wonder if that helps with @rzumer desync issues.

**Comment by tdaede** [comment]
Please rebase.

**Comment by tdaede** [comment]
I cherry-picked just the first commit and it speeds up the encoder by 2x with the default speed settings, and doesn't seem to cause any issues.

**Comment by negge** [comment]
Do we have any performance numbers for this patch?

**Comment by tdaede** [comment]
Replaced by #250

**Pull request closed without merging**
