### PR TITLE
Simplify further the API

### PR DESCRIPTION
**Pull request by lu-zero**
This should address the problem found by @dwbuiten (and incidentally make rav1e emit a last keyframe)

### CODE REVIEW

**Comment by tdaede** [comment]
What do you mean by "last keyframe?"

**Comment by kodabb** [comment]
@tdaede the very last frame of the stream is encoded as key

**Comment by shssoichiro** [comment]
Does the last keyframe output resolve some issue, or is it just incidental? I can see the side effect that it would (slightly) increase output filesize, but that's acceptable if it's needed to fix some issue.

**Comment by dwbuiten** [comment]
This PR causes some frames to go missing for me (using crav1e, at least) when encoding foreman_cif.y4m. Specifically frames 241, 242, and 243 vanish.

**Comment by lu-zero** [comment]
Let's drop it for now.

**Pull request closed without merging**
