### PR TITLE
Add heuristic quantizer adjustment

### PR DESCRIPTION
**Pull request by YaLTeR**
Introducing quantizer adjustment without speed loss.

[AWCY](https://beta.arewecompressedyet.com/?job=master-c8ca08c77c19514d251b497900d9a24e203caa0b&job=heuristic-sidx-2019-08-19_123457-9a6e4a7)

[AWCY vs. the RDO quantizers on --speed 2](https://beta.arewecompressedyet.com/?job=speed2-2019-08-19_131220-9a6e4a7&job=heuristic-sidx-speed2-2019-08-19_131918-69c0056): as expected, the RDO finds a solution that's slightly better.

### CODE REVIEW

**Comment by dwbuiten** [comment]
Can you add an explanation fo the heuristic in comments and/or commit message for future archaeologists?

**Comment by YaLTeR** [comment]
> Can you add an explanation of the heuristic in comments and/or commit message for future archaeologists?

There's a comment there:
```rust
// Chosen based on the RDO segment ID statistics for speed 2 on the DOTA2
// clip.
```
It's basically what it is—I made a histogram of segment ID vs. mean importance for that block from `--speed 2` on the DOTA2 clip, then set the heuristic constants based on that.

**Comment by YaLTeR** [comment]
Should I add this extended explanation into that comment?

**Comment by tdaede** [comment]
It would be nice to have, in particular people in the future will need to retune the heuristic as we make other improvements.

**Comment by YaLTeR** [comment]
Done.

**Pull request merged**
