### PR TITLE
Deduplicate checkpoint() calls in rdo_partition_decision()

### PR DESCRIPTION
**Pull request by ycho**
There is a slight speed gain with no change in bdrate.

[AWCY result](https://beta.arewecompressedyet.com/?job=master_de68ab_5f%402019-01-15T22%3A37%3A23.075Z&job=test0_topdown_refactor_chkpt_5f%402019-01-16T18%3A46%3A01.349Z)

### CODE REVIEW

**Comment by lu-zero** [comment]
probably you should mention why it is working :)

**Comment by ycho** [comment]
I had an commit message for this PR before your 1st message, but forgot to push it so just did it. :)
Thanks for review!

**Comment by ycho** [comment]
Before landing, doing further testing with speed 1.

**Comment by tdaede** [comment]
Did these beta runs work in the end?

**Comment by tdaede** [comment]
rip :( do you want to try again or should we just assume this is ok

**Comment by ycho** [comment]
Let me try re-run right now...

**Comment by ycho** [comment]
Also, running it for -s 1 as well.

**Comment by ycho** [comment]
No bdrate change at default speed -s 3, [AWCY](https://beta.arewecompressedyet.com/?job=test0_topdown_refactor_chkpt%402019-01-22T23%3A53%3A23.745Z&job=master_de68ab%402019-01-22T23%3A52%3A35.925Z).

Waiting for -s 1, but probably good to land now. If -s 1 result ever give regression, we can revert the commit.

**Comment by ycho** [comment]
NO bdrate change for -s 1 as well, but almost no speed gain at that speed.
[AWCY result](https://beta.arewecompressedyet.com/?job=master_de68ab_s1%402019-01-22T23%3A54%3A20.580Z&job=test0_topdown_refactor_chkpt_s1%402019-01-22T23%3A54%3A40.315Z)

**Pull request merged**
