### PR TITLE
Change header single bit writes to write_bit() calls

### LINKED ISSUE #379: Implement CONFIG_FILM_GRAIN

### PR DESCRIPTION
**Pull request by rzumer**
Replace `write(1, <0, 1>)` calls with `write_bit(<false, true>)` for consistency.

### CODE REVIEW

**Comment by rzumer** [comment]
I recommend rebasing this PR instead of squashing to keep the style change separate.

**Comment by tdaede** [comment]
please rebase

**Comment by tdaede** [comment]
one more rebase, sorry

**Comment by rzumer** [comment]
Why is a rebase needed?

**Pull request merged**
