### PR TITLE
Compute lambda from ac_q rather than dc_q

### PR DESCRIPTION
**Pull request by barrbrain**
The rationale is that RDO is dominated by AC coefficients in most sequences.

AWCY results at [default speed and tune=Psychovisual](https://beta.arewecompressedyet.com/?job=master-3d5389903a5c3166d6b3dbc5ec4b4b9a0e0a57fe&job=psy-lambda-ac-q%402019-02-07T14%3A35%3A10.099Z):

|    PSNR | PSNR Cb | PSNR Cr | PSNR HVS |    SSIM | MS SSIM | CIEDE 2000 |
|    ---: |    ---: |    ---: |     ---: |    ---: |    ---: |       ---: |
| -0.7150 | -5.1618 | -5.7443 |  -0.3831 | -1.1512 | -1.1489 |    -2.6864 |

AWCY results at [default speed and tune=Psnr](https://beta.arewecompressedyet.com/?job=psnr-3d5389903a5c3166d6b3dbc5ec4b4b9a0e0a57fe%402019-02-06T17%3A16%3A56.096Z&job=psnr-lambda-dc-q%402019-02-07T13%3A19%3A29.257Z):

|    PSNR | PSNR Cb | PSNR Cr | PSNR HVS |    SSIM | MS SSIM | CIEDE 2000 |
|    ---: |    ---: |    ---: |     ---: |    ---: |    ---: |       ---: |
| -2.6675 | -4.5719 | -5.0094 |  -2.0622 | -1.7526 | -1.4547 |    -3.2220 |

### CODE REVIEW

**Comment by tdaede** [comment]
Is there a way to prove the statement "RDO is dominated by AC"? Like can you show rate of AC vs DC? Can you average the AC and DC quantizers together?

**Comment by barrbrain** [comment]
My intuition is that the degree to which AC or DC dominate is variance-dependant. Averaging the quantizers is a quite reasonable for content-independence.

**Comment by tdaede** [comment]
Tim asked if you could try this on top of his flat quantizer patch.

**Comment by barrbrain** [comment]
Computing lambda from the geometric mean of `ac_q` and `dc_q` gives similar benefit for both Psnr and Psychovisual.

AWCY results at [default speed and tune=Psychovisual](https://beta.arewecompressedyet.com/?job=master-3d5389903a5c3166d6b3dbc5ec4b4b9a0e0a57fe&job=psy-lambda-ac-dc%402019-02-08T00%3A27%3A56.979Z):

|    PSNR | PSNR Cb | PSNR Cr | PSNR HVS |    SSIM | MS SSIM | CIEDE 2000 |
|    ---: |    ---: |    ---: |     ---: |    ---: |    ---: |       ---: |
| -1.1384 | -2.2778 | -3.1934 |  -0.9523 | -0.9442 | -0.8688 |    -1.5804 |

AWCY results at [default speed and tune=Psnr](https://beta.arewecompressedyet.com/?job=psnr-3d5389903a5c3166d6b3dbc5ec4b4b9a0e0a57fe%402019-02-06T17%3A16%3A56.096Z&job=psnr-lambda-ac-dc%402019-02-08T00%3A27%3A35.155Z):

|    PSNR | PSNR Cb | PSNR Cr | PSNR HVS |    SSIM | MS SSIM | CIEDE 2000 |
|    ---: |    ---: |    ---: |     ---: |    ---: |    ---: |       ---: |
| -1.8821 | -2.4596 | -3.2181 |  -1.5904 | -1.1773 | -0.9966 |    -2.0889 |

**Comment by barrbrain** [comment]
> Tim asked if you could try this on top of his flat quantizer patch.

This became https://github.com/barrbrain/rav1e/commit/rate-control-flatter-q

AWCY results at [default speed, tune=Psnr and matching rates](https://beta.arewecompressedyet.com/?job=psnr-3d5389903a5c3166d6b3dbc5ec4b4b9a0e0a57fe%402019-02-06T17%3A16%3A56.096Z&job=psnr-rc-flat-q-avg-altq%402019-02-08T15%3A27%3A38.577Z):

|    PSNR | PSNR Cb | PSNR Cr | PSNR HVS |    SSIM | MS SSIM | CIEDE 2000 |
|    ---: |    ---: |    ---: |     ---: |    ---: |    ---: |       ---: |
| -3.4829 |  4.9815 |  5.6464 |  -2.8428 | -2.6512 | -2.3131 |     0.7084 |

This is the total effect of flattening quantization and adjusting the target quantizers.
I'm closing this PR in favour of continuing that direction.

**Pull request closed without merging**
