### PR TITLE
Don't initialize planes used for downsampling.

### PR DESCRIPTION
**Pull request by tdaede**
Negligible speed impact.

### CODE REVIEW

**Comment by shssoichiro** [comment]
I forgot to PR the benchmarks I wrote for this function last night, but it's showing a 60% regression for downsampling on 8-bit input. Interestingly, 10-bit showed no such regression.

```
downsample_8bit         time:   [1.4270 ms 1.4326 ms 1.4391 ms]                             
                        change: [+57.070% +59.069% +61.065%] (p = 0.00 < 0.05)
                        Performance has regressed.
Found 14 outliers among 100 measurements (14.00%)
  1 (1.00%) low mild
  2 (2.00%) high mild
  11 (11.00%) high severe

downsample_10bit        time:   [922.60 us 929.11 us 935.82 us]                             
                        change: [+1.5419% +2.8097% +3.9266%] (p = 0.00 < 0.05)
                        Performance has regressed.
Found 9 outliers among 100 measurements (9.00%)
  6 (6.00%) high mild
  3 (3.00%) high severe
```

**Comment by tdaede** [comment]
So this moves the pad into downsample_from, because I wanted it to always return a fully initialized plane. You'll need to move the pad back out to get a fair comparison.

**Comment by tdaede** [comment]
Oh, it also moves the allocation into the function, so you'll have to undo that too. Or just change new_uninitialized to new.

**Comment by shssoichiro** [comment]
Okay, matching up the internals, `new_uninitialized` seems to be about 2% slower for 8-bit and 10% faster for 10-bit. For some reason.

**Comment by shssoichiro** [comment]
Feel free to merge whenever you're ready

**Pull request merged**
