### PR TITLE
Remove rate::ilog64()

### PR DESCRIPTION
**Pull request by rzumer**
It is superseded by `util.rs::ILog::ilog()`.

### CODE REVIEW

**Comment by lu-zero** [comment]
It exists because we cannot have const-fn traits in stable and that could be the case for a while =/

**Comment by rzumer** [comment]
Right, so one of #1465 and #1466 can be chosen, or add const fn functions for all required `PrimInts` besides i64.

**Comment by rzumer** [comment]
After discussing with @lu-zero he feels indifferent about it (correct me if I'm wrong) and I prefer this solution, since less duplicated code seems a bigger benefit than constifying a non-critical function. I will squash and push after CI succeeds.

**Comment by lu-zero** [comment]
It is better to have less lines of code around until the const-fn lands completely.

Keep in mind that it has an effect if the function arguments are constant themselves, otherwise it doesn't do anything :)

**Pull request merged**
