### PR TITLE
Constrain input y and stripe size to fit in frame

### PR DESCRIPTION
**Pull request by KyleSiefring**
Doesn't fix any bugs. Might give a tiny speedup.

Results: https://beta.arewecompressedyet.com/?job=master-5079a62a69ec62578452ead6b9d5e5022b37996e&job=test_new_bounds_lrf2%402019-07-17T19%3A46%3A51.020Z

### CODE REVIEW

**Comment by KyleSiefring** [comment]
Are either of the two comments still relevant? I think the first on is definitely not but I'm not sure about the first one.

**Comment by xiphmont** [comment]
....which two?  I see one in the diff...

**Comment by KyleSiefring** [comment]
The other is trailing a line of code.
This seems to have problems with odd sized videos. Hmm.

**Comment by KyleSiefring** [comment]
Okay, this should work.

**Pull request merged**
