### PR TITLE
Add rav1e_config_parse_bool

### PR DESCRIPTION
**Pull request by lu-zero**
Act as helper to set boolean values.

Fixes: https://github.com/xiph/rav1e/issues/2155

### CODE REVIEW

**Comment by dwbuiten** [comment]
I feel like using `parse_int` with 0 and 1 feels more like idiomatic C, but also I don't have a stong opinion on it.

@tdaede any opinion from you?

**Comment by lu-zero** [comment]
If you tested it I'd go and merge it

**Comment by lu-zero** [comment]
Poke.

**Comment by lu-zero** [comment]
I'd land it for 0.5.

**Pull request merged**
