### PR TITLE
Fix README command for running cargo bench.

### PR DESCRIPTION
**Pull request by tdaede**

### CODE REVIEW

**Comment by rzumer** [comment]
I guess that will not work on Windows. Why is this environment variable needed? Can't it be a default?

**Comment by tdaede** [comment]
It is for a pretty gross reason - the benches use non-pub functions, but can only "see" pub ones. So this exports everything pub.

We could make it a cargo --feature and that would make it work on windows. It's still hella gross though. I think there is a way to move the benches directly into the files and avoid this whole deal, still reading.

**Comment by tdaede** [comment]
https://github.com/rust-lang/rust/issues/50297

**Comment by tdaede** [comment]
I made it marginally less gross.

**Comment by lu-zero** [comment]
I made it _this_ ugly intentionally so we do not forget and `--all-features` won't be a huge surprise.

The avformat muxer made it already sufficiently surprising though...

**Comment by tdaede** [comment]
@lu-zero do you have a less bad solution?

**Comment by lu-zero** [comment]
We can go your way since the patch is ready and just document that `--all-features` should not be used.

**Comment by tdaede** [comment]
documented

**Pull request merged**
