### PR TITLE
Move scene change detection into ContextInner

### PR DESCRIPTION
**Pull request by shssoichiro**
It will need access to these fields for lookahead scene detection

### CODE REVIEW

**Comment by YaLTeR** [comment]
Why move it here, again? Also I'm not sure if we always have the last frame in `frame_q` to fetch it from there.

**Comment by shssoichiro** [comment]
This is related to #1441 / #794. When we use lookahead for scene change detection, it will need access to the whole lookahead queue instead of just the current and last frame. This also avoids having the scenechange detector keep an extra reference to the last frame, when we can look that up from the frame queue. Originally I hoped to change the ScenechangeDetector struct to hold a reference to the frame_q, but that wouldn't be possible without unsafe code or a major refactor.

I considered that the detect_scene_change function could just be a standalone function in the scenechange module, but it seemed unnecessary to keep that module for one small function.

Maybe it just makes more sense to close this until the full new scenechange algorithm is implemented. I wanted to keep the refactor separate from changing the algorithm, but maybe that doesn't make sense here.

**Comment by tdaede** [comment]
#1443 just landed, which by nature of constructing fi's in lookahead also effectively moved scenecut detection to lookahead. So maybe this refactor isn't necessary?

**Comment by shssoichiro** [comment]
I think some change still needs to be made here, because `SceneChangeDetector` still doesn't have access to all the frames. However, after looking through the AOM code more, this PR might also not do what we need without more refactoring. I'll hold off on this change for now until we can be more certain what the lookahead-based scenecut detection looks like.

**Pull request closed without merging**
