### PR TITLE
Unbreak the scenechange detection

### PR DESCRIPTION
**Pull request by lu-zero**
Pass all the frames in the buffer to the scenedetector only when in flushing state.

### CODE REVIEW

**Comment by shssoichiro** [comment]
This seems more complicated than the prior version (before the breaking change). Could you explain why you chose this implementation rather than reverting?

**Comment by lu-zero** [comment]
I prefer having the code explicit, alternatively I can revert and add a comment, but probably tomorrow, I'm falling asleep now ^^;

**Comment by lu-zero** [comment]
Here a tidier version, I'm still sold in making explicit the flush condition.

**Comment by lu-zero** [comment]
Appveyor got a networking issue but I have no mean to restart it =/

**Pull request merged**
