### PR TITLE
Enable some more useful Clippy lints

### PR DESCRIPTION
**Pull request by shssoichiro**
This is an ongoing WIP, I have many non-default lints that I'd like to enable because I believe they could be useful. Due to the amount of work and code changes, I'm splitting it up over multiple PRs over however many days it takes.

For now, this PR starts with:
- [doc_markdown](https://rust-lang.github.io/rust-clippy/master/index.html#doc_markdown)
- [missing_errors_doc](https://rust-lang.github.io/rust-clippy/master/index.html#missing_errors_doc)
- [missing_panics_doc](https://rust-lang.github.io/rust-clippy/master/index.html#missing_panics_doc)
- [undocumented_unsafe_blocks](https://rust-lang.github.io/rust-clippy/master/index.html#undocumented_unsafe_blocks)
- [missing_const_for_fn](https://rust-lang.github.io/rust-clippy/master/index.html#missing_const_for_fn)

### CODE REVIEW

**Comment by shssoichiro** [comment]
Note: Please do not squash this PR when merging, it is intentionally split into separate commits.

**Comment by lu-zero** [comment]
I like the idea, but it requires further fixes ^^

**Comment by shssoichiro** [comment]
@lu-zero this should have everything cleaned up now--CI passes all lints at least

**Review by redzic — APPROVED** [review]

**Comment by shssoichiro** [comment]
[Add more clippy lints to rav1e](https://trello.com/c/e92Xyl8q/1-add-more-clippy-lints-to-rav1e)

**Pull request merged**
