### PR TITLE
Merge dav1d.0.7.0

### PR DESCRIPTION
**Pull request by vibhoothiiaanand**
Hi,

This patchset merges dav1d 0.7.0's AArch64 and x86 Assembly functions

Changes being Introduced
```diff

+ arm64: ipred: Remove a superfluous postincrement
+ arm64: ipred: Avoid data dependencies with consecutive dup instructions
+ arm64: ipred: Do shifts on only half the register width when possible
+ arm64: ipred: Use rounded shifts instead of a separate addition
+ arm64: ipred: Integrate aggregation into the first pass of cfl_ac
+ arm: ipred: Remove stray leftover instructions
+ arm: ipred: Prepare for 16 bpc
+ arm64: ipred: Add NEON implementation of ipred for 16 bpc
+ arm64: mc: NEON implementation of emu_edge for 8bpc
+ arm64: mc: NEON implementation of emu_edge for 16bpc
+ arm: mc: NEON implementation of emu_edge for 8bpc
+ arm64: Explicitly forbid using the x18 register
+ arm64: itx: Remove a now unused macro
+ arm64: itx: Remove a todo comment about more special cased functions
+ arm64: itx: Remove an unused constant
+ arm64: itx: Cosmetic fix up
+ arm64: itx: Minor optimizations for the 8x32 functions
+ arm64: itx: Simplify inv_txfm_horz_dct_32x8
+ arm64: itx: Fix the eob checking for dct_dct_64x16
+ arm64: itx: Share code for the three horz_16x8 functions
+ arm64: itx: Prepare for other bitdepths
+ arm: Mark global symbols hidden
+ arm64: itx: Add NEON implementation of itx for 10 bpc
+ msac: Avoid attempting to refill after eob has already been reached
+ x86: add AVX2 SIMD for generate_grain_uv_{422,444}
+ x86: add SSSE3 SIMD for generate_grain_uv_{422,444}
+ x86: add AVX2 SIMD for ipred.cfl_ac[444]
+ meson/x86: add option to disable AVX-512 asm 
+ x86: add AVX2 version of mc.resize()
+ x86: add SSSE3 version of mc.resize()
+ x86: don't use vptest in SSSE3 version
+ x86: use btc instead of xor+test in fgy_32x32xn_avx2
+ x86: add AVX2 versions for filmgrain.fguv_32x32xn[422/444]
+ x86: use btc instead of xor+test or 32byte alignment in fgy_32x32xn_ssse3
+ x86: add SSSE3 versions for filmgrain.fguv_32x32xn[422/444]
+ x86: mc: Skip checks for zero leftext/rightext within the need_left_ext/need_right_ext blocks
+ x86: add some explanatory comment to wiener_filter_h
- x86: Add cdef_filter_{4,8}x8 AVX-512 (Ice Lake) asm
- x86: Split AVX2 / AVX-512 CDEF into dedicated files
+ x86: Remove identity/adst itx fast paths
+ x86: Eliminate redundant 3-operand register syntax in itx
+ msac: Avoid attempting to refill after eob has already been reached
- x86: Use 'test' instead of 'or' to compare with zero
```

From commit "meson/x86: add option to disable AVX-512 asm", we have excluded CDEF since we dav1d and rav1e has diverged.

This set has been extracting `arm` and `x86` separately.

Also, this has been compiled on both arm and x86, yet to do benchmarks.

### CODE REVIEW

**Comment by lu-zero** [comment]
Please fix https://github.com/xiph/rav1e/pull/2343/checks?check_run_id=716093048#step:5:61

**Comment by vibhoothiiaanand** [comment]
We did remove 
```diff
- meson/x86: add option to disable AVX-512 asm [1]
- x86: add AVX2 version of mc.resize() [2]
- x86: add SSSE3 version of mc.resize() [3]
- x86: don't use vptest in SSSE3 version [4]
- x86: Add cdef_filter_{4,8}x8 AVX-512 (Ice Lake) asm [5]
- x86: Split AVX2 / AVX-512 CDEF into dedicated files [6]
- x86: Use 'test' instead of 'or' to compare with zero [7]
```
commits because
+ CDEF from dav1d and rav1e has diverged so 7, 6, 5 is being dropped
+ For 1 it was dropped earlier as it was with CDEF and NASM check<2.14, when I was checking now saw it was there for mc.asm also, now question is, are we going to follow a similar pattern with regard to AVX512, if it is similar I could pick that commit and rebase this set over that following the same set, would require opinion over that.

**Comment by rzumer** [comment]
I would like to see benchmarks before merging personally, since I have noticed many PRs recently have been untested.

**Comment by vibhoothiiaanand** [comment]
@barrbrain 
+ I have updated the history to be aligned with dav1d changes.
+ Also the symbol commit c57ebcf at the end of aarch64 import is a bad idea since all the previous commits will be broken, so I had a quick discussion with @shssoichiro whether to squash it or break it.
So What I did right now is,
I have squashed it and made it clear in the commit message about it and as it is a symbol change, it would be wiser to have it together in a single commit instead of two,
Please do check the changes.

**Comment by barrbrain** [comment]
I tested at speed 10 on an x86 machine with a fairly stable CPU frequency. (Turbo disabled, governor powersave)
I saw a 0.13% increase in user time + system time, with around 0.2% variation between runs.
Overall, I would say no significant change to encoding time.

<details>

```
barrbrain@echidna ~/Workspace/rav1e $ cargo run --release ~/Videos/ducks_take_off_1080p50_60f.y4m -s 10 -o /dev/null --tile-rows 2 --threads 4 --benchmark
    Finished release [optimized + debuginfo] target(s) in 0.05s
     Running `target/x86_64-unknown-linux-musl/release/rav1e /home/barrbrain/Videos/ducks_take_off_1080p50_60f.y4m -s 10 -o /dev/null --tile-rows 2 --threads 4 --benchmark`
>  Using y4m decoder: 1920x1080p @ 50/1 fps, 4:2:0, 8-bit
>  Encoding settings: keyint_min=12 keyint_max=240 quantizer=100 bitrate=0 min_quantizer=0 low_latency=false tune=Psychovisual rdo_lookahead_frames=40 min_block_size=32x32 max_block_size=32x32 multiref=true fast_deblock=true reduced_tx_set=true tx_domain_distortion=false tx_domain_rate=false encode_bottomup=false rdo_tx_decision=false prediction_modes=Simple include_near_mvs=false no_scene_detection=false diamond_me=true cdef=true use_satd_subpel=false non_square_partition=false enable_timing_info=false fine_directional_intra=true
>  CPU Feature Level: AVX512
>  Using 2 tiles (1x2)
encoded 60 frames, 0.853 fps, 40868.75 Kb/s                    >  encoded 60 frames, 0.853 fps, 40868.75 Kb/s
>  ----------
>  Key frame:             1 | avg QP:  79.00 | avg size:  375091 B
>  Inter frame:          59 | avg QP: 134.00 | avg size:   97546 B
>  Intra only frame:      0 | avg QP:   0.00 | avg size:       0 B
>  Switching frame:       0 | avg QP:   0.00 | avg size:       0 B
>  ----
user time: 116.583702 s
system time: 2.459078 s
maximum rss: 1024368 KB
barrbrain@echidna ~/Workspace/rav1e $ cargo run --release ~/Videos/ducks_take_off_1080p50_60f.y4m -s 10 -o /dev/null --tile-rows 2 --threads 4 --benchmark
    Finished release [optimized + debuginfo] target(s) in 0.05s
     Running `target/x86_64-unknown-linux-musl/release/rav1e /home/barrbrain/Videos/ducks_take_off_1080p50_60f.y4m -s 10 -o /dev/null --tile-rows 2 --threads 4 --benchmark`
>  Using y4m decoder: 1920x1080p @ 50/1 fps, 4:2:0, 8-bit
>  Encoding settings: keyint_min=12 keyint_max=240 quantizer=100 bitrate=0 min_quantizer=0 low_latency=false tune=Psychovisual rdo_lookahead_frames=40 min_block_size=32x32 max_block_size=32x32 multiref=true fast_deblock=true reduced_tx_set=true tx_domain_distortion=false tx_domain_rate=false encode_bottomup=false rdo_tx_decision=false prediction_modes=Simple include_near_mvs=false no_scene_detection=false diamond_me=true cdef=true use_satd_subpel=false non_square_partition=false enable_timing_info=false fine_directional_intra=true
>  CPU Feature Level: AVX512
>  Using 2 tiles (1x2)
encoded 60 frames, 0.854 fps, 40868.75 Kb/s                    >  encoded 60 frames, 0.854 fps, 40868.75 Kb/s
>  ----------
>  Key frame:             1 | avg QP:  79.00 | avg size:  375091 B
>  Inter frame:          59 | avg QP: 134.00 | avg size:   97546 B
>  Intra only frame:      0 | avg QP:   0.00 | avg size:       0 B
>  Switching frame:       0 | avg QP:   0.00 | avg size:       0 B
>  ----
user time: 116.428839 s
system time: 2.373363 s
maximum rss: 1025088 KB
barrbrain@echidna ~/Workspace/rav1e $ git checkout 1dddab988f5ee1b5b5e69fb569774bf172444c1
a && cargo build --release
barrbrain@echidna ~/Workspace/rav1e $ cargo run --release ~/Videos/ducks_take_off_1080p50_60f.y4m -s 10 -o /dev/null --tile-rows 2 --threads 4 --benchmark
    Finished release [optimized + debuginfo] target(s) in 0.06s
     Running `target/x86_64-unknown-linux-musl/release/rav1e /home/barrbrain/Videos/ducks_take_off_1080p50_60f.y4m -s 10 -o /dev/null --tile-rows 2 --threads 4 --benchmark`
>  Using y4m decoder: 1920x1080p @ 50/1 fps, 4:2:0, 8-bit
>  Encoding settings: keyint_min=12 keyint_max=240 quantizer=100 bitrate=0 min_quantizer=0 low_latency=false tune=Psychovisual rdo_lookahead_frames=40 min_block_size=32x32 max_block_size=32x32 multiref=true fast_deblock=true reduced_tx_set=true tx_domain_distortion=false tx_domain_rate=false encode_bottomup=false rdo_tx_decision=false prediction_modes=Simple include_near_mvs=false no_scene_detection=false diamond_me=true cdef=true use_satd_subpel=false non_square_partition=false enable_timing_info=false fine_directional_intra=true
>  CPU Feature Level: AVX512
>  Using 2 tiles (1x2)
encoded 60 frames, 0.853 fps, 40868.75 Kb/s                    >  encoded 60 frames, 0.853 fps, 40868.75 Kb/s
>  ----------
>  Key frame:             1 | avg QP:  79.00 | avg size:  375091 B
>  Inter frame:          59 | avg QP: 134.00 | avg size:   97546 B
>  Intra only frame:      0 | avg QP:   0.00 | avg size:       0 B
>  Switching frame:       0 | avg QP:   0.00 | avg size:       0 B
>  ----
user time: 116.383503 s
system time: 2.425823 s
maximum rss: 1021368 KB
barrbrain@echidna ~/Workspace/rav1e $ cargo run --release ~/Videos/ducks_take_off_1080p50_60f.y4m -s 10 -o /dev/null --tile-rows 2 --threads 4 --benchmark
    Finished release [optimized + debuginfo] target(s) in 0.05s
     Running `target/x86_64-unknown-linux-musl/release/rav1e /home/barrbrain/Videos/ducks_take_off_1080p50_60f.y4m -s 10 -o /dev/null --tile-rows 2 --threads 4 --benchmark`
>  Using y4m decoder: 1920x1080p @ 50/1 fps, 4:2:0, 8-bit
>  Encoding settings: keyint_min=12 keyint_max=240 quantizer=100 bitrate=0 min_quantizer=0 low_latency=false tune=Psychovisual rdo_lookahead_frames=40 min_block_size=32x32 max_block_size=32x32 multiref=true fast_deblock=true reduced_tx_set=true tx_domain_distortion=false tx_domain_rate=false encode_bottomup=false rdo_tx_decision=false prediction_modes=Simple include_near_mvs=false no_scene_detection=false diamond_me=true cdef=true use_satd_subpel=false non_square_partition=false enable_timing_info=false fine_directional_intra=true
>  CPU Feature Level: AVX512
>  Using 2 tiles (1x2)
encoded 60 frames, 0.854 fps, 40868.75 Kb/s                    >  encoded 60 frames, 0.854 fps, 40868.75 Kb/s
>  ----------
>  Key frame:             1 | avg QP:  79.00 | avg size:  375091 B
>  Inter frame:          59 | avg QP: 134.00 | avg size:   97546 B
>  Intra only frame:      0 | avg QP:   0.00 | avg size:       0 B
>  Switching frame:       0 | avg QP:   0.00 | avg size:       0 B
>  ----
user time: 116.259388 s
system time: 2.465668 s
maximum rss: 1024752 KB
```
</details>

**Pull request merged**
