### PR TITLE
Adjust params of profile release to execution performance

### PR DESCRIPTION
**Pull request by Michael-Lfx**

### CODE REVIEW

**Comment by lu-zero** [comment]
It seems to break coveralls (maybe it is a travis glitch?), could you please mention the speedup in the commit?

**Comment by tdaede** [comment]
I think all of these are default on Release except for panic mode, but that one should only change code size?

**Comment by Michael-Lfx** [comment]
Yeah, `panic = "abort"` reduces the package size.

**Comment by tdaede** [comment]
I don't think the reduced binary size is justified by the reduced quality abort messages at this point in development.

**Pull request closed without merging**
