### PR TITLE
Use the correct macro designator

### PR DESCRIPTION
**Pull request by lu-zero**

### CODE REVIEW

**Comment by KyleSiefring** [comment]
I would love to know why this broke.

**Comment by barrbrain** [comment]
Probing locally with `cargo update`, I narrowed the cause to [paste v0.1.13](https://crates.io/crates/paste/0.1.13) which was released 9 hours ago.

**Comment by lu-zero** [comment]
In general the designators aren't strictly correct so would be a good idea to land this.

**Comment by jbeich** [comment]
Can you also backport to [0.3 branch](https://github.com/xiph/rav1e/commits/0.3)? Building from [v0.3.1 tag](https://github.com/xiph/rav1e/releases/tag/v0.3.1) (due to #1434) fails in a similar way:
```rust
error: expected expression, found `TxType::DCT_DCT`
   --> src/asm/x86/transform/inverse.rs:67:33
    |
67  |               out[get_tx_type_idx($ENUM)] = Some([<rav1e_inv_txfm_add_$TYPE2 _$TYPE1 _$W x $H _$OPT_LOWER>]);
    |                                   ^^^^^ expected expression
...
134 | / impl_itx_fns!(
135 | |   // 64x
136 | |   [(TxType::DCT_DCT, dct, dct)],
137 | |   [(64, 64), (64, 32), (32, 64), (16, 64), (64, 16)],
...   |
163 | |   [(avx2, AVX2), (ssse3, SSSE3)]
164 | | );
    | |__- in this macro invocation
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by lu-zero** [comment]
> Can you also backport to [0.3 branch](https://github.com/xiph/rav1e/commits/0.3)? For example, [v0.3.1 tag](https://github.com/xiph/rav1e/releases/tag/v0.3.1) is affected due to #1434:
> 
> ```rust
> error: expected expression, found `TxType::DCT_DCT`
>    --> src/asm/x86/transform/inverse.rs:67:33
>     |
> 67  |               out[get_tx_type_idx($ENUM)] = Some([<rav1e_inv_txfm_add_$TYPE2 _$TYPE1 _$W x $H _$OPT_LOWER>]);
>     |                                   ^^^^^ expected expression
> ...
> 134 | / impl_itx_fns!(
> 135 | |   // 64x
> 136 | |   [(TxType::DCT_DCT, dct, dct)],
> 137 | |   [(64, 64), (64, 32), (32, 64), (16, 64), (64, 16)],
> ...   |
> 163 | |   [(avx2, AVX2), (ssse3, SSSE3)]
> 164 | | );
>     | |__- in this macro invocation
>     |
>     = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
> ```

Sure

**Comment by ycho** [comment]
Thank you sou much for fixing this!

**Pull request merged**
